import type { ChipsFieldOptionsMap } from "@/config/chipsOptions/types";

export const ANIMAL_FIELD_OPTIONS_BY_SUBCATEGORY: Record<
  string,
  ChipsFieldOptionsMap
> = {
  // Pet Food & Accessories
  "cat-accessories": {
    accessory_type: [
      "Collar",
      "Leash",
      "Harness",
      "Litter Tray",
      "Carrier",
      "Scratcher",
    ],
    material: ["Plastic", "Metal", "Rubber", "Wood", "Fabric"],
    condition: ["New", "Used", "Like New"],
  },
  "dog-accessories": {
    accessory_type: [
      "Collar",
      "Leash",
      "Harness",
      "Muzzle",
      "Carrier",
      "Seat Belt",
    ],
    size: ["Small", "Medium", "Large", "Extra Large"],
    condition: ["New", "Used", "Like New"],
  },
  "beds-mats-houses": {
    type: ["Bed", "Mat", "House", "Tent"],
    size: ["Small", "Medium", "Large", "Extra Large"],
    material: ["Fabric", "Memory Foam", "Orthopedic", "Waterproof"],
    condition: ["New", "Used", "Like New"],
  },
  "dog-food": {
    brand: [
      "Pedigree",
      "Royal Canin",
      "Reflex",
      "Bonacibo",
      "Pro Plan",
      "Josera",
      "Drools",
      "SmartHeart",
    ],
    type: ["Dry Food", "Wet Food", "Semi-Wet"],
    age_group: ["Puppy", "Adult", "Senior", "All Ages"],
    condition: ["New", "Unopened"],
  },
  brooders: {
    capacity: ["300 Chicks", "500 Chicks", "1000 Chicks", "2000 Chicks"],
    type: ["Electric", "Gas", "Solar"],
    condition: ["New", "Used", "Refurbished"],
  },
  medicines: {
    type: [
      "Antibiotics",
      "Anti-inflammatory",
      "Vitamins",
      "Digestive",
      "Parasitic",
    ],
    condition: ["New", "Unopened"],
  },
  "pet-scratchers-furniture": {
    type: ["Scratcher", "Climbing Tree", "Perch", "Bed"],
    material: ["Sisal", "Carpet", "Wood", "Paper"],
    size: ["Small", "Medium", "Large"],
    condition: ["New", "Used", "Like New"],
  },
  "cat-toys": {
    toy_type: ["Ball", "Feather", "String", "Interactive", "Catnip Toy"],
    material: ["Plastic", "Rubber", "Fabric", "Feather"],
    condition: ["New", "Used"],
  },
  "bowls-feeders": {
    type: ["Water Bowl", "Food Bowl", "Double Bowl", "Automatic Feeder"],
    material: ["Ceramic", "Plastic", "Stainless Steel", "Glass"],
    condition: ["New", "Used", "Like New"],
  },
  "carriers-travel": {
    carrier_type: ["Hard Shell", "Soft Shell", "Backpack", "Rolling Carrier"],
    size: ["Small", "Medium", "Large"],
    material: ["Plastic", "Metal", "Fabric"],
    condition: ["New", "Used", "Like New"],
  },
  "clothing-shoes-accessories": {
    item_type: ["Sweater", "Jacket", "Boot", "Collar", "Leash"],
    size: ["XS", "S", "M", "L", "XL"],
    material: ["Cotton", "Wool", "Synthetic", "Leather"],
    condition: ["New", "Used", "Like New"],
  },
  "fish-food": {
    brand: ["Tetra", "Sera", "Hikari", "Taiyo", "Aqua One", "Generic"],
    type: ["Flakes", "Pellets", "Frozen", "Live", "Tablets"],
    condition: ["New", "Unopened"],
  },
  "litter-cleanup-sanitation": {
    product_type: ["Litter", "Waste Bags", "Deodorizer", "Cleaner", "Scoop"],
    condition: ["New", "Used"],
  },
  "dental-healthcare": {
    product_type: ["Toothbrush", "Toothpaste", "Dental Treats", "Mouthwash"],
    condition: ["New"],
  },
  "dog-toys": {
    toy_type: ["Ball", "Rope", "Chew Toy", "Interactive", "Plush"],
    material: ["Rubber", "Rope", "Plastic", "Fabric", "Plush"],
    size: ["Small", "Medium", "Large"],
    condition: ["New", "Used"],
  },
  "training-aids": {
    aid_type: [
      "Training Clicker",
      "Training Treats",
      "Training Collar",
      "Leash",
    ],
    condition: ["New", "Used"],
  },
  technology: {
    device_type: ["GPS Tracker", "Smart Collar", "Camera", "Water Bowl Feeder"],
    condition: ["New", "Used", "Refurbished"],
  },
  "cages-crates-doors": {
    cage_type: ["Metal Cage", "Plastic Cage", "Wood Crate", "Wire Pen"],
    size: ["Small", "Medium", "Large", "Extra Large"],
    material: ["Metal", "Plastic", "Wood", "Wire"],
    condition: ["New", "Used", "Like New"],
  },
  "hen-cages": {
    capacity: ["10 Birds", "20 Birds", "50 Birds", "100+ Birds"],
    size: ["Small", "Medium", "Large", "Extra Large"],
    material: ["Metal", "Wood", "Plastic", "Mixed"],
    condition: ["New", "Used", "Refurbished"],
  },
  incubators: {
    capacity: ["48 Eggs", "96 Eggs", "192 Eggs", "Large Capacity"],
    type: ["Automatic", "Manual", "Semi-Automatic"],
    condition: ["New", "Used", "Refurbished"],
  },
  aquariums: {
    size: ["10L", "25L", "50L", "75L", "100L+"],
    type: ["Freshwater", "Saltwater", "Planted"],
    material: ["Glass", "Acrylic"],
    condition: ["New", "Used", "Like New"],
  },
  "birds-accessories": {
    accessory_type: ["Perch", "Mirror", "Swing", "Toy", "Food Bowl"],
    material: ["Wood", "Plastic", "Metal", "Natural"],
    size: ["Small", "Medium", "Large"],
    condition: ["New", "Used"],
  },
  "pet-grooming": {
    condition: ["New"],
  },
  "birds-food": {
    brand: [
      "Versele-Laga",
      "Vitakraft",
      "Kaytee",
      "Tropican",
      "Polo",
      "Generic",
    ],
    type: ["Seeds", "Pellets", "Mix", "Organic"],
    condition: ["New", "Unopened"],
  },
  "cat-food": {
    brand: [
      "Whiskas",
      "Royal Canin",
      "Me-O",
      "Reflex",
      "Purina",
      "Bonacibo",
      "Pro Plan",
      "Josera",
    ],
    type: ["Dry Food", "Wet Food", "Semi-Wet"],
    age_group: ["Kitten", "Adult", "Senior", "All Ages"],
    condition: ["New", "Unopened"],
  },

  // Livestock
  goats: {
    gender: ["Male", "Female", "Mixed"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local", "Imported", "Cross-breed"],
    condition: ["Excellent", "Good", "Fair"],
  },
  cows: {
    gender: ["Male", "Female"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local Desi", "Imported Holstein", "Cross-breed"],
    condition: ["Excellent", "Good", "Fair"],
  },
  sheep: {
    gender: ["Male", "Female", "Mixed"],
    wool_quality: ["Fine", "Medium", "Coarse", "Mixed"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local", "Imported"],
    condition: ["Excellent", "Good", "Fair"],
  },
  bulls: {
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local", "Imported"],
    condition: ["Excellent", "Good", "Fair"],
  },
  buffalos: {
    gender: ["Male", "Female"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local", "Imported"],
    condition: ["Excellent", "Good", "Fair"],
  },
  camels: {
    gender: ["Male", "Female", "Mixed"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local Desert", "Imported"],
    condition: ["Excellent", "Good", "Fair"],
  },
  horses: {
    color: ["Bay", "Black", "Chestnut", "Gray", "Palomino", "Mixed"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local", "Imported Arabian", "Imported Thoroughbred"],
    condition: ["Excellent", "Good", "Fair"],
  },
  donkeys: {
    gender: ["Male", "Female", "Mixed"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local", "Imported"],
    condition: ["Excellent", "Good", "Fair"],
  },
  pigs: {
    gender: ["Male", "Female", "Mixed"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local", "Imported"],
    condition: ["Excellent", "Good", "Fair"],
  },
  poultry: {
    bird_type: ["Chicken", "Duck", "Turkey", "Guinea Fowl", "Quail"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local", "Imported Breed"],
    condition: ["Excellent", "Good", "Fair"],
  },
  rabbits: {
    gender: ["Male", "Female", "Mixed"],
    color: ["White", "Black", "Brown", "Gray", "Mixed"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    condition: ["Excellent", "Good", "Fair"],
  },
  alpacas: {
    gender: ["Male", "Female"],
    fiber_quality: ["Premium", "Good", "Fair"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local Bred", "Imported"],
    condition: ["Excellent", "Good", "Fair"],
  },
  others: {
    health_status: ["Healthy", "Good Health", "Fair Health"],
    origin: ["Local", "Imported"],
    condition: ["Excellent", "Good", "Fair"],
  },
  "other-animals": {
    animal_group: [
      "Mammal",
      "Reptile",
      "Amphibian",
      "Farm Animal",
      "Exotic",
      "Pet Animal",
      "Other",
    ],
    gender: ["Male", "Female", "Mixed", "Unknown"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local", "Imported", "Cross-breed"],
    condition: ["Excellent", "Good", "Fair"],
  },
  "other-birds": {
    bird_type: [
      "Parrot",
      "Canary",
      "Finch",
      "Lovebird",
      "Cockatiel",
      "Macaw",
      "Falcon",
      "Owl",
      "Pigeon",
      "Other",
    ],
    gender: ["Male", "Female", "Pair", "Unknown"],
    color: ["White", "Black", "Green", "Mixed"],
    health_status: ["Healthy", "Good Health", "Fair Health"],
    vaccination_status: [
      "Fully Vaccinated",
      "Partially Vaccinated",
      "Not Vaccinated",
    ],
    origin: ["Local", "Imported", "Bred in Captivity"],
    cage_included: ["Yes", "No"],
    condition: ["Excellent", "Good", "Fair"],
  },
};
