import type { ChipsFieldOptionsMap } from "@/config/chipsOptions/types";

export const BOOKS_SPORTS_HOBBIES_FIELD_OPTIONS_BY_SUBCATEGORY: Record<
  string,
  ChipsFieldOptionsMap
> = {
  "gym-fitness": {
    condition: ["New", "Used", "Like New"],
    type: [
      "Dumbbells",
      "Barbells",
      "Kettlebells",
      "Weight Plates",
      "Machine",
      "Mat",
      "Other",
    ],
    equipment_type: [
      "Free Weights",
      "Machines",
      "Cardio",
      "Bodyweight",
      "Wearable",
    ],
    usage: ["Home", "Commercial", "Professional"],
  },

  "sports-equipment": {
    condition: ["New", "Used", "Like New", "Good"],
    type: [
      "Cricket",
      "Football",
      "Badminton",
      "Tennis",
      "Basketball",
      "Volleyball",
      "Other",
    ],
    sport_type: [
      "Cricket",
      "Football",
      "Badminton",
      "Tennis",
      "Basketball",
      "Volleyball",
      "Swimming",
      "Cycling",
      "Skating",
      "Other",
    ],
    size: ["XS", "S", "M", "L", "XL", "XXL"],
    material: ["Rubber", "Leather", "Synthetic", "Nylon", "Plastic", "Canvas"],
  },

  "other-hobbies": {
    condition: ["New", "Used", "Like New", "Vintage"],
    type: [
      "Art & Craft",
      "Board Games",
      "Collectibles",
      "Model Kits",
      "Musical Instrument",
      "Reading",
      "Photography",
      "Other",
    ],
    hobby_category: [
      "Art & Craft",
      "Games",
      "Collectibles",
      "Toys",
      "Music",
      "Reading",
      "Photography",
      "Video Games",
      "DIY",
      "Other",
    ],
    age_group: ["Kids (3-7)", "Kids (8-12)", "Teens", "Adults", "All Ages"],
  },

  calendars: {
    condition: ["New", "Used"],
    type: ["Wall Calendar", "Desk Calendar", "Planner", "Perpetual Calendar"],
    format: ["2024", "2025", "2026", "Perpetual"],
    theme: [
      "Nature",
      "Animals",
      "Sports",
      "Movies",
      "Art",
      "Travel",
      "Business",
      "Inspirational",
      "Plain",
      "Other",
    ],
  },

  books: {
    condition: ["New", "Used", "Like New", "Good"],
    type: [
      "Textbook",
      "Novel",
      "Reference",
      "Children",
      "Religious",
      "Comics",
      "Other",
    ],
    language: ["English", "Urdu", "Arabic", "Hindi", "Bilingual", "Other"],
    book_type: ["Hardcover", "Paperback", "eBook", "Workbook", "Guide"],
    features: [
      "Original",
      "Imported",
      "Signed",
      "Limited Edition",
      "Illustrated",
    ],
  },
  "stationery-items": {
    condition: ["New", "Used", "Like New"],
    type: ["Writing", "Office", "School", "Art", "Other"],
    language: ["N/A"],
    stationery_type: [
      "Pens",
      "Pencils",
      "Markers",
      "Files",
      "Notebooks",
      "Staplers",
      "Other",
    ],
    pack_size: ["Single", "Pack of 3", "Pack of 6", "Pack of 12", "Bulk"],
    features: ["Branded", "Imported", "Eco Friendly", "Waterproof"],
  },
  calculators: {
    condition: ["New", "Used", "Like New"],
    type: ["Student", "Scientific", "Graphing", "Financial", "Business"],
    language: ["N/A"],
    calculator_type: [
      "Basic",
      "Scientific",
      "Graphing",
      "Printing",
      "Financial",
    ],
    power_source: ["Battery", "Solar", "Battery + Solar"],
    features: ["Original", "Case Included", "Dual Power", "Exam Approved"],
  },
  magazines: {
    condition: ["New", "Used", "Like New"],
    type: [
      "Fashion",
      "Business",
      "Technology",
      "Sports",
      "Lifestyle",
      "Kids",
      "Other",
    ],
    language: ["English", "Urdu", "Other"],
    magazine_type: ["Monthly", "Weekly", "Special Edition", "Archive"],
    frequency: ["Weekly", "Monthly", "Quarterly", "Annual"],
    features: ["Original", "Imported", "Collector Issue", "Sealed"],
  },
  dictionaries: {
    condition: ["New", "Used", "Like New"],
    type: ["Language", "Technical", "Medical", "Legal", "School"],
    language: ["English", "Urdu", "Arabic", "French", "Other"],
    dictionary_type: [
      "Monolingual",
      "Bilingual",
      "Picture",
      "Pocket",
      "Comprehensive",
    ],
    language_level: ["Beginner", "Intermediate", "Advanced", "All Levels"],
    features: ["Latest Edition", "Illustrated", "Hardcover", "Compact"],
  },

  "party-supplies": {
    condition: ["New", "Used", "Like New"],
    type: ["Decor", "Tableware", "Balloons", "Props", "Other"],
    material: ["Paper", "Plastic", "Foil", "Fabric", "Mixed"],
    pack_size: ["Single", "Pack of 5", "Pack of 10", "Pack of 25", "Bulk"],
    supply_type: [
      "Balloons",
      "Banners",
      "Candles",
      "Confetti",
      "Party Hats",
      "Disposable Set",
    ],
    event_type: ["Birthday", "Wedding", "Baby Shower", "Eid", "Corporate"],
    features: ["Theme Based", "Premium", "Reusable", "Eco Friendly"],
  },
  "paper-products": {
    condition: ["New", "Used"],
    type: [
      "Art Paper",
      "Craft Paper",
      "Cardstock",
      "Origami",
      "Wrapping",
      "Other",
    ],
    material: ["Paper", "Kraft", "Cardboard", "Recycled"],
    pack_size: ["10 Sheets", "25 Sheets", "50 Sheets", "100 Sheets", "Roll"],
    paper_type: ["A4", "A3", "Cardstock", "Glossy", "Matte", "Textured"],
    size: ["A5", "A4", "A3", "12x12", "Custom"],
    features: ["Acid Free", "Recycled", "Premium", "Water Resistant"],
  },
  "painting-supplies": {
    condition: ["New", "Used", "Like New"],
    type: ["Paint", "Brush", "Canvas", "Palette", "Set"],
    material: ["Acrylic", "Oil", "Watercolor", "Mixed Media"],
    pack_size: ["Single", "Set of 6", "Set of 12", "Set of 24", "Combo"],
    paint_type: ["Acrylic", "Oil", "Watercolor", "Poster", "Spray"],
    surface_type: ["Canvas", "Paper", "Wood", "Wall", "Fabric"],
    features: ["Non-toxic", "Artist Grade", "Beginner Friendly", "Fast Dry"],
  },
  "gifts-wrapping": {
    condition: ["New", "Used", "Like New"],
    type: ["Gift Wrap", "Gift Bags", "Boxes", "Tags", "Ribbons"],
    material: ["Paper", "Foil", "Fabric", "Jute", "Plastic"],
    pack_size: ["Single", "Pack of 5", "Pack of 10", "Bundle"],
    item_type: [
      "Wrapping Paper",
      "Gift Bag",
      "Gift Box",
      "Gift Tags",
      "Ribbon Set",
    ],
    occasion: ["Birthday", "Wedding", "Eid", "Anniversary", "General"],
    features: ["Premium Finish", "Reusable", "Waterproof", "Handmade"],
  },
  "craft-packaging-supplies": {
    condition: ["New", "Used"],
    type: ["Packaging", "Labeling", "Sealing", "Storage"],
    material: ["Kraft", "Plastic", "Cardboard", "Jute", "Foam"],
    pack_size: ["Pack of 10", "Pack of 25", "Pack of 50", "Bulk"],
    packaging_type: [
      "Boxes",
      "Pouches",
      "Labels",
      "Tape",
      "Stickers",
      "Bubbles",
    ],
    features: ["Eco Friendly", "Customizable", "Tamper Proof", "Reusable"],
  },
  "art-pads-diaries-folios": {
    condition: ["New", "Used", "Like New"],
    type: ["Art Pad", "Diary", "Folio", "Notebook", "Sketchbook"],
    material: ["Paper", "Leather", "Synthetic", "Hardboard"],
    pack_size: ["Single", "Pack of 2", "Pack of 5"],
    product_type: ["Sketch Pad", "Diary", "Portfolio", "Journal", "Planner"],
    paper_size: ["A5", "A4", "A3", "B5", "Custom"],
    features: ["Hard Cover", "Spiral", "Acid Free", "Premium Paper"],
  },
  "modeling-sculpting": {
    condition: ["New", "Used", "Like New"],
    type: ["Clay", "Resin", "Tools", "Molds", "Kits"],
    material: ["Clay", "Polymer", "Resin", "Plaster", "Metal"],
    pack_size: ["Single", "Small Kit", "Medium Kit", "Large Kit"],
    sculpting_type: [
      "Clay Modeling",
      "Resin Casting",
      "Plaster",
      "Wood Carving",
      "Stone Carving",
    ],
    tool_included: ["Yes", "No"],
    features: [
      "Beginner Kit",
      "Professional Grade",
      "Non-toxic",
      "Reusable Molds",
    ],
  },

  "wool-knitting-crochet": {
    condition: ["New", "Used", "Like New"],
    type: ["Yarn", "Needles", "Hooks", "Knitting Set", "Crochet Set"],
    material: ["Wool", "Cotton", "Acrylic", "Bamboo", "Mixed"],
    pack_size: ["Single", "Pack of 3", "Pack of 6", "Bundle"],
    product_type: [
      "Yarn",
      "Knitting Needles",
      "Crochet Hooks",
      "Pattern Book",
      "Complete Kit",
    ],
    yarn_weight: ["Lace", "Light", "Medium", "Bulky", "Super Bulky"],
    features: ["Soft", "Imported", "Colorfast", "Handmade Friendly"],
  },
  "other-craft-supplies": {
    condition: ["New", "Used", "Like New"],
    type: ["DIY", "Craft Tool", "Embellishment", "Adhesive", "Other"],
    material: ["Plastic", "Wood", "Metal", "Paper", "Mixed"],
    pack_size: ["Single", "Pack of 5", "Pack of 10", "Bulk"],
    craft_type: [
      "Sewing",
      "Paper Craft",
      "Resin",
      "Jewelry",
      "Mixed Media",
      "Other",
    ],
    features: ["Reusable", "Imported", "Premium", "Eco Friendly"],
  },
  "laces-ribbons-decorative-trims": {
    condition: ["New", "Used"],
    type: ["Laces", "Ribbons", "Trims", "Borders", "Decorative Tapes"],
    material: ["Cotton", "Satin", "Silk", "Polyester", "Lace"],
    pack_size: ["1 Meter", "5 Meter", "10 Meter", "Roll"],
    trim_type: ["Lace", "Ribbon", "Piping", "Fringe", "Beaded Trim"],
    width: ["Narrow", "Medium", "Wide", "Mixed"],
    features: ["Colorfast", "Handwash", "Machine Washable", "Decorative"],
  },
  "quilt-making-supplies": {
    condition: ["New", "Used", "Like New"],
    type: ["Fabric", "Batting", "Thread", "Tools", "Pattern"],
    material: ["Cotton", "Polyester", "Wool", "Blends"],
    pack_size: ["Quarter Pack", "Half Meter", "1 Meter", "Bundle"],
    supply_type: [
      "Quilt Fabric",
      "Batting",
      "Quilting Thread",
      "Cutting Mat",
      "Ruler",
    ],
    quilt_size: ["Baby", "Single", "Double", "Queen", "King"],
    features: [
      "Pre-cut",
      "Premium Fabric",
      "Color Coordinated",
      "Beginner Friendly",
    ],
  },
  "sewing-accessories": {
    condition: ["New", "Used", "Like New"],
    type: ["Needles", "Threads", "Scissors", "Buttons", "Zippers", "Other"],
    material: ["Metal", "Plastic", "Cotton", "Polyester", "Mixed"],
    pack_size: ["Single", "Pack of 5", "Pack of 10", "Kit"],
    accessory_type: [
      "Needles",
      "Bobbins",
      "Scissors",
      "Buttons",
      "Zippers",
      "Measuring Tape",
    ],
    features: ["Rust Resistant", "Durable", "Imported", "Professional"],
  },
  "embroidery-hand-stitching": {
    condition: ["New", "Used", "Like New"],
    type: ["Threads", "Hoops", "Needles", "Kits", "Patterns"],
    material: ["Cotton", "Silk", "Polyester", "Metal", "Wood"],
    pack_size: ["Single", "Pack of 3", "Pack of 6", "Set"],
    embroidery_type: [
      "Hand Embroidery",
      "Cross Stitch",
      "Machine Embroidery",
      "Punch Needle",
    ],
    fabric_type: ["Cotton", "Linen", "Canvas", "Silk", "Mixed"],
    features: [
      "Beginner Kit",
      "Premium Threads",
      "Color Chart",
      "Pattern Included",
    ],
  },
  "sewing-craft-patterns": {
    condition: ["New", "Used", "Like New"],
    type: ["Sewing", "Knitting", "Crochet", "Embroidery", "Mixed"],
    material: ["Paper", "Digital", "Mixed"],
    pack_size: ["Single", "Pack of 5", "Pack of 10", "Bundle"],
    pattern_type: ["Dress", "Kids Wear", "Quilt", "Crochet", "Home Decor"],
    format: ["Printed", "Digital PDF", "Both"],
    features: [
      "Step-by-step",
      "Illustrated",
      "Beginner Friendly",
      "Multi-size",
    ],
  },

  lighting: {
    condition: ["New", "Used", "Like New"],
    type: ["Camping", "Hiking", "Emergency", "Tool"],
    capacity: ["Single", "Family", "Large Group"],
    material: ["Plastic", "Aluminum", "Steel", "Mixed"],
    lighting_type: [
      "Headlamp",
      "Lantern",
      "Torch",
      "String Light",
      "Rechargeable Lamp",
    ],
    power_source: ["Battery", "Rechargeable", "Solar", "Dual"],
    features: [
      "Water Resistant",
      "Long Battery",
      "Rechargeable",
      "High Lumens",
    ],
  },
  "trekking-poles": {
    condition: ["New", "Used", "Like New"],
    type: ["Single Pole", "Pair", "Trail Pole", "Nordic Pole"],
    capacity: ["Light", "Medium", "Heavy Duty"],
    material: ["Aluminum", "Carbon Fiber", "Steel"],
    pole_type: ["Folding", "Telescopic", "Fixed", "Shock Absorbing"],
    adjustable: ["Yes", "No"],
    features: ["Anti-shock", "Ergonomic Grip", "Carbide Tip", "Lightweight"],
  },
  "camp-kitchen": {
    condition: ["New", "Used", "Like New"],
    type: ["Cookware", "Stove", "Utensils", "Bottle", "Cooler"],
    capacity: ["1 Person", "2 Persons", "4 Persons", "Family"],
    material: ["Steel", "Aluminum", "Titanium", "Plastic"],
    kitchen_item_type: [
      "Stove",
      "Cook Set",
      "Mug",
      "Cutlery",
      "Cooler",
      "Kettle",
    ],
    fuel_type: ["Gas", "Solid Fuel", "Electric", "Multi Fuel"],
    features: ["Portable", "Foldable", "Heat Resistant", "Non-stick"],
  },
  "sleeping-gear": {
    condition: ["New", "Used", "Like New"],
    type: ["Sleeping Bag", "Pad", "Blanket", "Pillow", "Mat"],
    capacity: ["Single", "Double"],
    material: ["Polyester", "Down", "Foam", "Cotton"],
    sleeping_item_type: [
      "Sleeping Bag",
      "Sleeping Pad",
      "Camp Pillow",
      "Camp Blanket",
    ],
    temperature_rating: ["0C", "-5C", "-10C", "10C", "Summer"],
    features: ["Lightweight", "Water Resistant", "Compact", "Insulated"],
  },
  "camping-hiking-tool-kits": {
    condition: ["New", "Used", "Like New"],
    type: ["Multi-tool", "Knife Kit", "Repair Kit", "Survival Kit"],
    capacity: ["Mini", "Standard", "Pro"],
    material: ["Steel", "Aluminum", "Mixed"],
    tool_kit_type: ["Survival", "Repair", "Cooking", "Navigation", "First Aid"],
    features: ["Multi-purpose", "Compact", "Rust Resistant", "Carry Pouch"],
  },
  tents: {
    condition: ["New", "Used", "Like New"],
    type: ["Dome", "Cabin", "Pop-up", "Tunnel", "Backpacking"],
    capacity: ["1P", "2P", "3-4P", "5-6P", "6+P"],
    material: ["Polyester", "Nylon", "Canvas"],
    tent_type: ["Dome", "Tunnel", "Pop-up", "Family Tent", "Ultralight"],
    persons_capacity: ["1", "2", "3", "4", "5+"],
    features: ["Waterproof", "Double Layer", "Quick Setup", "UV Protected"],
  },
  backpacks: {
    condition: ["New", "Used", "Like New"],
    type: ["Daypack", "Hiking", "Trekking", "Travel", "Hydration"],
    capacity: ["20L", "30L", "40L", "50L", "60L+"],
    material: ["Nylon", "Polyester", "Canvas", "Leather"],
    backpack_type: [
      "Daypack",
      "Hiking Pack",
      "Trekking Pack",
      "Tactical",
      "Hydration",
    ],
    volume: ["10-20L", "20-30L", "30-40L", "40-50L", "50L+"],
    features: ["Waterproof", "Rain Cover", "Chest Strap", "Laptop Sleeve"],
  },
  "navigation-electronics": {
    condition: ["New", "Used", "Like New"],
    type: ["GPS", "Compass", "Radio", "Power Bank", "Tracker"],
    capacity: ["Personal", "Group"],
    material: ["Plastic", "Metal", "Mixed"],
    device_type: [
      "GPS Device",
      "Compass",
      "Two-way Radio",
      "Power Bank",
      "Satellite Communicator",
    ],
    battery_life: ["Up to 6h", "6-12h", "12-24h", "24h+"],
    features: ["Waterproof", "Solar Charging", "Offline Maps", "SOS Function"],
  },
  "shelters-canopies": {
    condition: ["New", "Used", "Like New"],
    type: ["Canopy", "Tarpaulin", "Shade", "Shelter"],
    capacity: ["Small", "Medium", "Large"],
    material: ["Polyester", "Nylon", "Canvas", "PVC"],
    shelter_type: ["Canopy", "Tarp Shelter", "Beach Shelter", "Awning"],
    features: ["UV Resistant", "Waterproof", "Quick Setup", "Portable"],
  },
  "camp-furniture": {
    condition: ["New", "Used", "Like New"],
    type: ["Chair", "Table", "Cot", "Stool", "Storage Rack"],
    capacity: ["Single", "Double", "Family"],
    material: ["Aluminum", "Steel", "Plastic", "Wood", "Fabric"],
    furniture_type: ["Chair", "Table", "Bed", "Stool", "Organizer"],
    foldable: ["Yes", "No"],
    features: ["Lightweight", "Foldable", "Carry Bag", "Rust Resistant"],
  },

  "coins-notes": {
    condition: ["Mint", "Excellent", "Good", "Fair"],
    category: ["Coin", "Bank Note", "Set", "Commemorative", "Rare"],
    origin: ["Local", "International", "Mixed"],
    grade: ["UNC", "XF", "VF", "F"],
    features: ["Rare", "Limited", "Certified", "Historical"],
  },
  stamps: {
    condition: ["Mint", "Used", "Fine", "Very Fine"],
    category: ["Postal", "Commemorative", "First Day Cover", "Sheet", "Rare"],
    origin: ["Local", "International", "Mixed"],
    features: ["Sealed", "Album Kept", "Limited", "Historical"],
  },
  stones: {
    condition: ["New", "Natural", "Polished", "Vintage"],
    category: ["Gemstone", "Crystal", "Mineral", "Decorative", "Raw"],
    origin: ["Local", "Imported", "Mixed"],
    stone_type: ["Quartz", "Agate", "Amethyst", "Jade", "Onyx", "Other"],
    features: ["Natural", "Certified", "Polished", "Collector Piece"],
  },
};
