import type { ChipsFieldOptionsMap } from "@/config/chipsOptions/types";

export const FASHION_BEAUTY_FIELD_OPTIONS_BY_SUBCATEGORY: Record<
  string,
  ChipsFieldOptionsMap
> = {
  watches: {
    condition: ["New", "Used", "Like New", "Open Box"],
    gender: ["Men", "Women", "Unisex"],
    movement: ["Quartz", "Automatic", "Mechanical", "Solar"],
    strap_material: ["Leather", "Metal", "Rubber", "Fabric", "Silicone"],
  },

  footwear: {
    condition: ["New", "Used", "Like New", "Open Box"],
    gender: ["Men", "Women", "Kids", "Unisex"],
    type: ["Casual", "Sports", "Formal", "Sandals", "Boots", "Slippers"],
    material: ["Leather", "Canvas", "Rubber", "Synthetic", "Suede"],
    size: ["5", "6", "7", "8", "9", "10", "11", "12", "13"],
  },

  jewellery: {
    condition: ["New", "Used", "Vintage"],
    gender: ["Men", "Women", "Unisex"],
    type: ["Necklace", "Bracelet", "Ring", "Earrings", "Anklet", "Pendant"],
    material: ["Gold", "Silver", "Platinum", "Copper", "Crystal", "Beads"],
    stone_type: ["Diamond", "Emerald", "Ruby", "Sapphire", "Pearl", "None"],
  },

  bags: {
    condition: ["New", "Used", "Like New", "Open Box"],
    gender: ["Men", "Women", "Unisex"],
    type: [
      "Handbag",
      "Backpack",
      "Shoulder Bag",
      "Crossbody",
      "Clutch",
      "Wallet",
    ],
    material: ["Leather", "Canvas", "Synthetic", "Fabric"],
    size: ["Small", "Medium", "Large", "Extra Large"],
  },

  fragrance: {
    condition: ["New", "Used", "Sealed"],
    gender: ["Men", "Women", "Unisex"],
    fragrance_type: [
      "Perfume",
      "Eau de Parfum",
      "Eau de Toilette",
      "Cologne",
      "Body Spray",
    ],
    volume: ["30ml", "50ml", "75ml", "100ml", "150ml", "200ml"],
    concentration: ["High", "Medium", "Low"],
  },

  "other-fashion": {
    condition: ["New", "Used", "Like New"],
    gender: ["Men", "Women", "Kids", "Unisex"],
    type: ["Belts", "Scarves", "Hats", "Gloves", "Sunglasses", "Ties", "Other"],
  },

  "diy-jewellery": {
    condition: ["New", "Used", "Open Box"],
    gender: ["Men", "Women", "Kids", "Unisex"],
    kit_type: ["Beading Kit", "Wire Wrapping", "Polymer Clay", "Resin Cast"],
    material: ["Beads", "Wire", "Clay", "Resin", "String"],
    skill_level: ["Beginner", "Intermediate", "Advanced"],
  },

  "clothes-eastern": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    type: ["Kurta", "Shalwar Kameez", "Saree", "Lehenga", "Suit", "Other"],
    size: ["XS", "S", "M", "L", "XL", "XXL"],
    fabric: ["Lawn", "Cotton", "Chiffon", "Silk", "Linen", "Velvet"],
    stitching: ["Stitched", "Unstitched", "Semi-Stitched"],
  },
  "clothes-western": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    type: ["Shirt", "T-Shirt", "Jeans", "Dress", "Jacket", "Skirt", "Other"],
    size: ["XS", "S", "M", "L", "XL", "XXL"],
    fabric: ["Cotton", "Denim", "Linen", "Polyester", "Silk", "Blended"],
    fit: ["Slim", "Regular", "Relaxed", "Oversized"],
  },
  "clothes-kids": {
    condition: ["New", "Used", "Like New"],
    gender: ["Boys", "Girls", "Unisex"],
    type: [
      "T-Shirts",
      "Shirts",
      "Pants",
      "Dresses",
      "Sets",
      "Nightwear",
      "Other",
    ],
    age_group: ["0-1Y", "1-3Y", "3-5Y", "5-8Y", "8+Y"],
    size: ["0-3M", "3-6M", "6-12M", "1-2Y", "3-4Y", "5-6Y", "7-8Y"],
    season: ["Summer", "Winter", "All Season"],
  },
  "clothes-intimates": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    intimate_type: [
      "Bra",
      "Panty",
      "Inner Vest",
      "Thermal",
      "Shapewear",
      "Nightwear",
    ],
    size: ["S", "M", "L", "XL", "XXL", "Free Size"],
    fabric: ["Cotton", "Lace", "Silk", "Nylon", "Spandex", "Modal"],
  },
  "clothes-hijabs-abayas": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Girls"],
    hijab_abaya_type: ["Hijab", "Abaya", "Niqab", "Khimar", "Prayer Set"],
    fabric: ["Chiffon", "Georgette", "Nida", "Cotton", "Jersey", "Silk"],
    size: ["S", "M", "L", "XL", "Free Size"],
  },
  "clothes-sports": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    sportswear_type: [
      "Track Suit",
      "Gym Wear",
      "Jersey",
      "Shorts",
      "Leggings",
      "Other",
    ],
    size: ["XS", "S", "M", "L", "XL", "XXL"],
    sport: ["Gym", "Football", "Cricket", "Running", "Yoga", "Cycling"],
  },
  "clothes-costumes": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Kids", "Unisex"],
    costume_type: [
      "Character",
      "Cultural",
      "Stage",
      "Themed",
      "Cosplay",
      "Other",
    ],
    size: ["XS", "S", "M", "L", "XL"],
    occasion: [
      "Birthday",
      "School Event",
      "Wedding",
      "Party",
      "Theater",
      "Other",
    ],
  },
  "clothing-accessories": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Kids", "Unisex"],
    accessory_type: [
      "Buttons",
      "Patches",
      "Brooches",
      "Pins",
      "Suspenders",
      "Other",
    ],
    material: ["Metal", "Plastic", "Fabric", "Leather", "Mixed"],
  },

  sunglasses: {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    frame_type: ["Aviator", "Wayfarer", "Round", "Cat Eye", "Square", "Sports"],
    lens_type: ["Polarized", "UV400", "Gradient", "Mirrored", "Photochromic"],
    uv_protection: ["Yes", "No"],
  },
  caps: {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Kids", "Unisex"],
    cap_type: [
      "Baseball",
      "Snapback",
      "Beanie",
      "Bucket",
      "Visor",
      "Sports Cap",
    ],
    size: ["Small", "Medium", "Large", "Adjustable", "Free Size"],
    material: ["Cotton", "Polyester", "Wool", "Denim", "Leather"],
  },
  "other-accessories": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Kids", "Unisex"],
    accessory_type: ["Band", "Hair Clip", "Pin", "Chain", "Charm", "Other"],
    material: ["Metal", "Plastic", "Fabric", "Leather", "Mixed"],
  },
  socks: {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Kids", "Unisex"],
    sock_type: ["Ankle", "Crew", "Knee High", "No Show", "Sports", "Thermal"],
    size: ["Kids", "Small", "Medium", "Large", "Free Size"],
    pack_size: ["Single Pair", "Pack of 3", "Pack of 5", "Pack of 10"],
  },
  belts: {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    belt_type: ["Casual", "Formal", "Waist Belt", "Braided", "Reversible"],
    material: ["Leather", "Synthetic", "Canvas", "Fabric", "Metal"],
    size: ["28", "30", "32", "34", "36", "38", "40+"],
  },
  gloves: {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    glove_type: ["Winter", "Driving", "Sports", "Formal", "Fingerless"],
    material: ["Leather", "Wool", "Cotton", "Synthetic", "Rubber"],
    size: ["Small", "Medium", "Large", "XL"],
  },
  eyewear: {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    eyewear_type: ["Reading Glasses", "Blue Light", "Prescription", "Fashion"],
    lens_type: ["Single Vision", "Bifocal", "Progressive", "Blue Cut", "Clear"],
    frame_material: ["Metal", "Plastic", "Titanium", "Acetate", "Mixed"],
  },
  scarves: {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    scarf_type: ["Winter Scarf", "Stole", "Shawl", "Wrap", "Bandana"],
    material: ["Cotton", "Wool", "Silk", "Chiffon", "Pashmina", "Acrylic"],
    size: ["Small", "Medium", "Large", "Free Size"],
  },
  cufflinks: {
    condition: ["New", "Used", "Like New"],
    gender: ["Men", "Unisex"],
    material: ["Steel", "Silver", "Gold Plated", "Brass", "Alloy"],
    finish: ["Matte", "Glossy", "Polished", "Textured"],
  },
  ties: {
    condition: ["New", "Used", "Like New"],
    gender: ["Men", "Unisex"],
    tie_type: ["Necktie", "Bow Tie", "Skinny Tie", "Cravat"],
    material: ["Silk", "Polyester", "Cotton", "Wool", "Linen"],
    width: ["Skinny", "Regular", "Wide"],
  },
  "key-holder": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    key_holder_type: [
      "Keychain",
      "Leather Holder",
      "Car Key Cover",
      "Wall Holder",
    ],
    material: ["Leather", "Metal", "Silicone", "Wood", "Plastic"],
  },

  "makeup-face": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    product_type: [
      "Foundation",
      "Concealer",
      "Primer",
      "Blush",
      "Highlighter",
      "Powder",
    ],
    skin_tone: ["Fair", "Light", "Medium", "Tan", "Deep"],
    finish: ["Matte", "Dewy", "Natural", "Luminous"],
    coverage: ["Light", "Medium", "Full"],
  },
  "other-makeup-accessories": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    accessory_type: [
      "Sponges",
      "Puffs",
      "Organizers",
      "Cases",
      "Mirrors",
      "Other",
    ],
    material: ["Foam", "Silicone", "Plastic", "Metal", "Mixed"],
  },
  "makeup-nails": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    product_type: [
      "Nail Polish",
      "Gel Polish",
      "Nail Art",
      "Remover",
      "Nail Care",
    ],
    finish: ["Glossy", "Matte", "Glitter", "Metallic", "Shimmer"],
    color_family: ["Red", "Pink", "Nude", "Black", "Blue", "Green", "Other"],
  },
  "makeup-eyes": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    product_type: [
      "Eyeliner",
      "Mascara",
      "Eyeshadow",
      "Brow Product",
      "Lashes",
    ],
    finish: ["Matte", "Shimmer", "Glossy", "Waterproof"],
    shade_family: ["Neutral", "Warm", "Cool", "Smokey", "Colorful"],
  },
  "makeup-lips": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    product_type: [
      "Lipstick",
      "Lip Gloss",
      "Lip Tint",
      "Lip Liner",
      "Lip Balm",
    ],
    finish: ["Matte", "Glossy", "Satin", "Velvet", "Cream"],
    shade_family: ["Nude", "Pink", "Red", "Brown", "Berry", "Coral", "Other"],
  },
  "makeup-brushes": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    brush_type: [
      "Face Brush",
      "Eye Brush",
      "Lip Brush",
      "Fan Brush",
      "Complete Set",
    ],
    bristle_type: ["Synthetic", "Natural", "Mixed"],
    set_size: ["Single", "3-Piece", "5-Piece", "10-Piece", "15+ Piece"],
  },

  "lotions-moisturisers": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    product_type: ["Body Lotion", "Moisturizer", "Body Butter", "Cream", "Gel"],
    skin_type: ["Dry", "Oily", "Combination", "Sensitive", "All Skin Types"],
    volume: ["50ml", "100ml", "200ml", "300ml", "500ml+"],
  },
  "hair-removal": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    method_type: [
      "Wax",
      "Cream",
      "Razor",
      "Trimmer",
      "Epilator",
      "Laser Device",
    ],
    body_area: ["Face", "Arms", "Legs", "Underarms", "Bikini", "Full Body"],
    skin_type: ["Sensitive", "Normal", "All Skin Types"],
  },
  "soaps-shower-gels": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    product_type: [
      "Soap",
      "Body Wash",
      "Shower Gel",
      "Syndet Bar",
      "Kids Wash",
    ],
    skin_type: ["Dry", "Oily", "Combination", "Sensitive", "All Skin Types"],
    fragrance_family: ["Floral", "Citrus", "Woody", "Fresh", "Unscented"],
  },
  "bath-body-accessories": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    accessory_type: [
      "Loofah",
      "Bath Brush",
      "Body Sponge",
      "Soap Dispenser",
      "Travel Kit",
    ],
    material: ["Silicone", "Plastic", "Wood", "Cotton", "Mixed"],
  },
  scrubs: {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    scrub_type: ["Face Scrub", "Body Scrub", "Lip Scrub", "Foot Scrub"],
    skin_type: ["Dry", "Oily", "Combination", "Sensitive", "All Skin Types"],
  },
  "massage-oils": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    oil_type: [
      "Aromatherapy",
      "Herbal",
      "Relaxation",
      "Pain Relief",
      "Baby Oil",
    ],
    body_area: ["Full Body", "Head", "Back", "Feet", "Joint"],
    volume: ["50ml", "100ml", "200ml", "300ml", "500ml+"],
  },
  "gifts-value-sets": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    set_type: [
      "Makeup Set",
      "Skincare Set",
      "Bath Set",
      "Fragrance Set",
      "Combo",
    ],
    target_gender: ["Women", "Men", "Unisex"],
  },

  "hair-care": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    product_type: [
      "Shampoo",
      "Conditioner",
      "Hair Oil",
      "Serum",
      "Mask",
      "Treatment",
    ],
    hair_type: ["Straight", "Wavy", "Curly", "Coily", "All Hair Types"],
    concern: [
      "Hair Fall",
      "Dandruff",
      "Dryness",
      "Frizz",
      "Damage Repair",
      "Volume",
    ],
  },
  "skin-care": {
    condition: ["New", "Used", "Sealed"],
    gender: ["Women", "Men", "Unisex"],
    product_type: [
      "Cleanser",
      "Toner",
      "Serum",
      "Moisturizer",
      "Sunscreen",
      "Mask",
    ],
    skin_type: ["Dry", "Oily", "Combination", "Sensitive", "All Skin Types"],
    concern: [
      "Acne",
      "Pigmentation",
      "Hydration",
      "Aging",
      "Brightening",
      "Pores",
    ],
  },
  "hair-accessories": {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Girls", "Unisex"],
    accessory_type: [
      "Hair Clip",
      "Hair Band",
      "Scrunchie",
      "Claw Clip",
      "Pins",
      "Headband",
    ],
    material: ["Plastic", "Metal", "Fabric", "Satin", "Mixed"],
  },

  bridals: {
    condition: ["New", "Used", "Like New"],
    gender: ["Women"],
    bridal_type: ["Lehenga", "Maxi", "Gown", "Sharara", "Farshi", "Other"],
    size: ["XS", "S", "M", "L", "XL", "Custom"],
    stitching: ["Stitched", "Unstitched", "Semi-Stitched"],
  },
  formals: {
    condition: ["New", "Used", "Like New"],
    gender: ["Women", "Men", "Unisex"],
    formal_type: [
      "Suit",
      "Blazer",
      "Formal Dress",
      "Shirt",
      "Trouser",
      "Other",
    ],
    size: ["XS", "S", "M", "L", "XL", "XXL"],
    fabric: ["Cotton", "Linen", "Silk", "Wool", "Polyester", "Blended"],
  },
  grooms: {
    condition: ["New", "Used", "Like New"],
    gender: ["Men"],
    groom_wear_type: [
      "Sherwani",
      "Prince Coat",
      "Suit",
      "Kurta Set",
      "Waistcoat",
    ],
    size: ["S", "M", "L", "XL", "XXL", "Custom"],
    stitching: ["Stitched", "Unstitched", "Semi-Stitched"],
  },
};
