import type { ChipsFieldOptionsMap } from "@/config/chipsOptions/types";

export const KIDS_FIELD_OPTIONS_BY_SUBCATEGORY: Record<string, ChipsFieldOptionsMap> =
  {
    toys: {
      condition: ["New", "Used", "Like New", "Good"],
      age_group: [
        "0-1 years",
        "1-3 years",
        "3-5 years",
        "5-8 years",
        "8+ years",
      ],
      toy_type: [
        "Action Figures",
        "Building Blocks",
        "Dolls",
        "Puzzles",
        "Board Games",
        "Educational Toys",
        "Outdoor Toys",
        "Remote Control",
        "Plush Toys",
        "Other",
      ],
      material: ["Plastic", "Wood", "Metal", "Fabric", "Rubber", "Mixed"],
    },

    "swing-slides": {
      condition: ["New", "Used", "Like New", "Good"],
      age_group: ["0-2 years", "2-5 years", "5-8 years", "8+ years"],
      equipment_type: [
        "Swing",
        "Slide",
        "Seesaws",
        "Climbing Frame",
        "Sandbox",
        "Spring Riders",
        "Jungle Gym",
        "Other",
      ],
      material: ["Plastic", "Wood", "Metal", "Steel"],
      size: ["Small", "Medium", "Large"],
    },

    "kids-accessories": {
      condition: ["New", "Used", "Like New"],
      age_group: [
        "0-1 years",
        "1-3 years",
        "3-5 years",
        "5-8 years",
        "8+ years",
      ],
      accessory_type: [
        "Backpack",
        "Shoes",
        "Socks",
        "Hat",
        "Jacket",
        "Bag",
        "Belt",
        "Scarf",
        "Mittens",
        "Other",
      ],
      size: ["XS", "S", "M", "L", "XL"],
    },

    "kids-furniture": {
      condition: ["New", "Used", "Like New"],
      age_group: [
        "0-2 years",
        "2-5 years",
        "5-8 years",
        "8+ years",
        "All Ages",
      ],
      furniture_type: [
        "Crib",
        "Bed",
        "High Chair",
        "Playpen",
        "Desk",
        "Chair",
        "Bookshelf",
        "Wardrobe",
        "Other",
      ],
      material: ["Wood", "Plastic", "Metal", "Fabric"],
    },

    "bath-diapers": {
      condition: ["New", "Sealed", "Unused"],
      age_group: [
        "0-6 months",
        "6-12 months",
        "1-2 years",
        "2-3 years",
        "3+ years",
      ],
      product_type: [
        "Diapers",
        "Wipes",
        "Bath Tub",
        "Bath Seat",
        "Towels",
        "Shampoo & Soap",
        "Lotion & Oil",
        "Potty Seat",
        "Other",
      ],
      size: [
        "Size 1",
        "Size 2",
        "Size 3",
        "Size 4",
        "Size 5",
        "Size 6",
        "One Size",
      ],
    },

    "kids-clothes": {
      condition: ["New", "Used", "Like New", "Good"],
      age_group: [
        "0-1 years",
        "1-3 years",
        "3-5 years",
        "5-8 years",
        "8+ years",
      ],
      clothing_type: [
        "Shirts & Tops",
        "T-Shirts",
        "Pants & Trousers",
        "Jeans",
        "Dresses",
        "Nightwear",
        "Sweaters",
        "Jackets",
        "Sets",
        "Other",
      ],
      size: ["0-3M", "3-6M", "6-12M", "1-2Y", "3-4Y", "5-6Y", "7-8Y", "9-10Y"],
      gender: ["Boys", "Girls", "Unisex"],
      season: ["Summer", "Winter", "All Season"],
      features: [
        "Cotton",
        "Imported",
        "Brand New",
        "Soft Fabric",
        "Machine Washable",
      ],
    },

    "kids-shoes": {
      condition: ["New", "Used", "Like New", "Good"],
      age_group: [
        "0-1 years",
        "1-3 years",
        "3-5 years",
        "5-8 years",
        "8+ years",
      ],
      shoe_type: [
        "Sneakers",
        "Sandals",
        "School Shoes",
        "Boots",
        "Slippers",
        "Sports Shoes",
        "Formal Shoes",
      ],
      size: [
        "EU 20",
        "EU 22",
        "EU 24",
        "EU 26",
        "EU 28",
        "EU 30",
        "EU 32",
        "EU 34",
      ],
      gender: ["Boys", "Girls", "Unisex"],
      closure_type: ["Lace", "Velcro", "Slip-On", "Buckle"],
      features: [
        "Non-slip",
        "Waterproof",
        "Lightweight",
        "Breathable",
        "Orthopedic",
      ],
    },

    "kids-clothing-others": {
      condition: ["New", "Used", "Like New", "Good"],
      age_group: [
        "0-1 years",
        "1-3 years",
        "3-5 years",
        "5-8 years",
        "8+ years",
      ],
      category: [
        "Clothes",
        "Shoes",
        "Costumes",
        "Uniforms",
        "Accessories",
        "Other",
      ],
      size: ["XS", "S", "M", "L", "XL", "One Size"],
      features: [
        "Branded",
        "Imported",
        "Soft Fabric",
        "Premium Quality",
        "Limited Edition",
      ],
    },

    "kids-costumes": {
      condition: ["New", "Used", "Like New"],
      age_group: ["1-3 years", "3-5 years", "5-8 years", "8+ years"],
      costume_type: [
        "Superhero",
        "Princess",
        "Animal",
        "Cultural",
        "Fantasy",
        "Cartoon Character",
        "Other",
      ],
      size: ["S", "M", "L", "XL"],
      occasion: ["School Event", "Birthday", "Fancy Dress", "Eid", "Halloween"],
      features: [
        "Accessories Included",
        "Washable",
        "Comfort Fit",
        "Premium Fabric",
      ],
    },

    "kids-uniforms": {
      condition: ["New", "Used", "Like New"],
      age_group: ["3-5 years", "5-8 years", "8+ years"],
      uniform_type: [
        "School Uniform",
        "Sports Uniform",
        "College Uniform",
        "Tuition Uniform",
        "Other",
      ],
      size: ["S", "M", "L", "XL"],
      institution_type: ["School", "Academy", "College", "Sports Club"],
      features: ["Stitched", "Unstitched", "Name Tag", "Set Included"],
    },

    "prams-walkers": {
      condition: ["New", "Used", "Like New"],
      age_group: ["0-6 months", "6-12 months", "1-2 years", "2+ years"],
      gear_type: ["Pram", "Stroller", "Walker", "Jogger", "Travel System"],
      weight_capacity: ["Up to 10kg", "Up to 15kg", "Up to 20kg", "20kg+"],
      foldable: ["Yes", "No"],
      features: [
        "Reclining Seat",
        "Cup Holder",
        "Storage Basket",
        "Canopy",
        "Shock Absorber",
      ],
    },

    "baby-cots": {
      condition: ["New", "Used", "Like New"],
      age_group: ["0-6 months", "6-12 months", "1-2 years", "2+ years"],
      cot_type: ["Wooden Cot", "Portable Cot", "Crib", "Co-Sleeper", "Playard"],
      material: ["Wood", "Metal", "Plastic", "Mixed"],
      size: ["Small", "Medium", "Large"],
      features: [
        "Adjustable Height",
        "Mosquito Net",
        "Storage Drawer",
        "Mattress Included",
      ],
    },

    "baby-swings": {
      condition: ["New", "Used", "Like New"],
      age_group: ["0-6 months", "6-12 months", "1-2 years"],
      swing_type: ["Electric Swing", "Manual Swing", "Rocker", "Bouncer Swing"],
      power_source: ["Battery", "Electric", "Manual"],
      safety_harness: ["Yes", "No"],
      features: ["Music", "Timer", "Remote", "Multiple Speed", "Toy Bar"],
    },

    "other-baby-gear": {
      condition: ["New", "Used", "Like New"],
      age_group: ["0-6 months", "6-12 months", "1-2 years", "2+ years"],
      gear_category: [
        "Feeding",
        "Sleep",
        "Safety",
        "Travel",
        "Bath",
        "Health",
        "Other",
      ],
      features: ["Branded", "Imported", "BPA Free", "Lightweight", "Portable"],
    },

    "high-chairs": {
      condition: ["New", "Used", "Like New"],
      age_group: ["6-12 months", "1-2 years", "2+ years"],
      chair_type: [
        "Feeding Chair",
        "Booster Seat",
        "Convertible Chair",
        "Portable Chair",
      ],
      material: ["Plastic", "Metal", "Wood", "Mixed"],
      foldable: ["Yes", "No"],
      features: [
        "Adjustable Height",
        "Removable Tray",
        "Seat Belt",
        "Easy Clean",
      ],
    },

    "baby-carriers": {
      condition: ["New", "Used", "Like New"],
      age_group: ["0-6 months", "6-12 months", "1-2 years"],
      carrier_type: [
        "Soft Carrier",
        "Structured Carrier",
        "Wrap",
        "Sling",
        "Hip Seat",
      ],
      carry_position: ["Front", "Back", "Hip", "Multi Position"],
      weight_capacity: ["Up to 10kg", "Up to 15kg", "Up to 20kg"],
      features: [
        "Breathable Fabric",
        "Waist Support",
        "Padded Straps",
        "Newborn Insert",
      ],
    },

    "car-seats": {
      condition: ["New", "Used", "Like New"],
      age_group: ["0-1 years", "1-3 years", "3-5 years", "5+ years"],
      seat_type: ["Infant", "Convertible", "Booster", "All-in-One"],
      group_stage: ["Group 0", "Group 0+", "Group 1", "Group 2", "Group 3"],
      isofix: ["Yes", "No"],
      features: [
        "Side Impact Protection",
        "Reclining",
        "Harness",
        "Washable Cover",
      ],
    },

    "baby-bouncers": {
      condition: ["New", "Used", "Like New"],
      age_group: ["0-6 months", "6-12 months", "1-2 years"],
      bouncer_type: [
        "Manual Bouncer",
        "Electric Bouncer",
        "Rocker",
        "Vibrating Seat",
      ],
      power_source: ["Battery", "Electric", "Manual"],
      weight_capacity: ["Up to 9kg", "Up to 12kg", "Up to 18kg"],
      features: ["Music", "Vibration", "Toy Bar", "Adjustable Recline"],
    },

    "kids-cars": {
      condition: ["New", "Used", "Like New"],
      age_group: ["1-3 years", "3-5 years", "5-8 years"],
      vehicle_type: [
        "Ride-On Car",
        "Remote Control Car",
        "Jeep",
        "ATV",
        "Truck",
      ],
      power_type: ["Battery", "Manual", "Pedal"],
      battery_life: ["Up to 30 mins", "30-60 mins", "1-2 hours", "2+ hours"],
      features: [
        "Remote Control",
        "Lights",
        "Music",
        "Seat Belt",
        "Dual Motor",
      ],
    },

    "kids-cycles": {
      condition: ["New", "Used", "Like New"],
      age_group: ["2-4 years", "4-6 years", "6-9 years", "9+ years"],
      cycle_type: ["Balance Bike", "Tricycle", "Bicycle", "BMX"],
      wheel_size: [
        "12 inch",
        "14 inch",
        "16 inch",
        "18 inch",
        "20 inch",
        "24 inch",
      ],
      training_wheels: ["Yes", "No"],
      features: [
        "Basket",
        "Bell",
        "Training Wheels",
        "Adjustable Seat",
        "Brake System",
      ],
    },

    "kids-bikes": {
      condition: ["New", "Used", "Like New"],
      age_group: ["3-5 years", "5-8 years", "8+ years"],
      bike_type: [
        "Mini Bike",
        "Dirt Bike",
        "Electric Bike",
        "Pocket Bike",
        "ATV Bike",
      ],
      engine_capacity: ["50cc", "70cc", "100cc", "Electric"],
      safety_features: [
        "Limiter",
        "Helmet Included",
        "Knee Guards",
        "Speed Lock",
        "Safety Brake",
      ],
      features: ["Starter", "Suspension", "Disc Brake", "Low Noise"],
    },

    "kids-scooties": {
      condition: ["New", "Used", "Like New"],
      age_group: ["3-5 years", "5-8 years", "8+ years"],
      scooty_type: [
        "Manual Scooter",
        "Electric Scooter",
        "3-Wheel Scooter",
        "Kick Scooter",
      ],
      power_type: ["Manual", "Battery", "Electric"],
      battery_life: ["Up to 30 mins", "30-60 mins", "1-2 hours", "2+ hours"],
      features: [
        "Foldable",
        "LED Wheels",
        "Height Adjustable",
        "Brake",
        "Bluetooth",
      ],
    },
  };
