import type { ChipsFieldOptionsMap } from "@/config/chipsOptions/types";

export const MOBILE_FIELDS_OPTIONS_BY_SUBCATEGORY: Record<
  string,
  ChipsFieldOptionsMap
> = {
  "mobile-phones": {
    condition: ["New", "Used", "Open Box", "Refurbished"],
    pta_status: ["PTA Approved", "Non PTA"],
    storage: ["32GB", "64GB", "128GB", "256GB", "512GB", "1TB"],
    ram: ["2GB", "3GB", "4GB", "6GB", "8GB", "12GB", "16GB"],
    battery: ["Below 3000mAh", "3000-4000mAh", "4000-5000mAh", "Above 5000mAh"],
    warranty: ["Yes", "No"],
  },
  tablets: {
    condition: ["New", "Used", "Open Box", "Refurbished"],
    storage: ["32GB", "64GB", "128GB", "256GB", "512GB"],
    ram: ["2GB", "3GB", "4GB", "6GB", "8GB"],
    warranty: ["Yes", "No"],
  },
  "smart-watches": {
    condition: ["New", "Used", "Open Box"],
    warranty: ["Yes", "No"],
  },
  "landline-phones": {
    condition: ["New", "Used"],
    warranty: ["Yes", "No"],
  },
  accessories: {
    condition: ["New", "Used", "Open Box"],
    warranty: ["Yes", "No"],
  },
  earphones: {
    brand: [
      "Sony",
      "JBL",
      "Skullcandy",
      "Beats",
      "Bose",
      "Sennheiser",
      "Anker",
      "Boat",
      "Realme",
      "Poco",
    ],
    type: ["Wired", "Wireless", "Neckband"],
    connectivity: ["3.5mm", "Type-C", "Lightning", "Bluetooth"],
    origin: ["Original", "Compatible", "Duplicate"],
    condition: ["New", "Used", "Open Box"],
    warranty: ["Yes", "No"],
  },
  "covers-cases": {
    brand: [
      "Spigen",
      "Nillkin",
      "OtterBox",
      "UAG",
      "Tech21",
      "Casetify",
      "Mous",
      "Pitaka",
      "Baseus",
      "ESR",
    ],
    case_type: ["Back Cover", "Flip Cover", "Pouch", "Bumper"],
    material: ["Silicone", "Leather", "Plastic", "Hard Shell"],
    origin: ["Original", "Compatible", "Local Brand"],
    condition: ["New", "Used", "Open Box"],
  },
  chargers: {
    brand: [
      "Anker",
      "Baseus",
      "UGREEN",
      "Spigen",
      "Belkin",
      "Aukey",
      "Reno",
      "Poco",
      "Samsung",
      "Apple",
    ],
    charger_type: ["Wall Charger", "Wireless Charger", "Car Charger"],
    connector_type: [
      "USB-C",
      "Lightning",
      "Micro USB",
      "Type-A",
      "Wireless Pad",
    ],
    power_output: ["5W", "10W", "18W", "20W", "25W", "33W", "65W"],
    origin: ["Original", "Compatible", "Refurbished"],
    condition: ["New", "Used", "Open Box"],
    warranty: ["Yes", "No"],
  },
  "other-accessories": {
    condition: ["New", "Used", "Open Box"],
    warranty: ["Yes", "No"],
  },
  headphones: {
    brand: [
      "Sony",
      "JBL",
      "Skullcandy",
      "Beats",
      "Bose",
      "Sennheiser",
      "Audio-Technica",
      "Boat",
      "Realme",
      "Pixel",
    ],
    type: ["Over-Ear", "On-Ear", "Gaming", "Studio"],
    connectivity: ["3.5mm", "Type-C", "Bluetooth"],
    origin: ["Original", "Compatible", "Duplicate"],
    condition: ["New", "Used", "Open Box"],
    warranty: ["Yes", "No"],
  },
  "power-banks": {
    brand: [
      "Anker",
      "Baseus",
      "UGREEN",
      "Belkin",
      "Aukey",
      "Samsung",
      "Poco",
      "Realme",
      "Moto",
      "Ambrane",
    ],
    capacity: ["5000mAh", "10000mAh", "20000mAh", "30000mAh"],
    output_ports: ["USB-A", "USB-C", "Multiple Ports"],
    input_ports: ["Micro USB", "USB-C", "Lightning"],
    origin: ["Original", "Compatible", "Refurbished"],
    condition: ["New", "Used", "Open Box"],
    warranty: ["Yes", "No"],
  },
  "charging-cables": {
    cable_type: ["Type-C", "Micro USB", "Lightning", "Type-C to Type-C"],
    length: ["0.5m", "1m", "1.5m", "2m"],
    origin: ["Original", "Compatible", "Premium Quality"],
    condition: ["New", "Used", "Open Box"],
  },
  "screen-protectors": {
    protector_type: ["Tempered Glass", "Privacy", "Matte", "Hydrogel"],
    coverage: ["Full Coverage", "Partial", "Edge-to-Edge"],
    origin: ["Original", "Compatible", "Generic"],
    condition: ["New", "Used", "Open Box"],
  },
  screens: {
    screen_type: ["OLED", "AMOLED", "LCD", "Touch Panel"],
    origin: ["Original", "Compatible", "Aftermarket"],
    condition: ["New", "Used", "Refurbished"],
    warranty: ["Yes", "No"],
  },
  "mobile-stands": {
    stand_type: ["Desk Stand", "Tripod", "Car Mount", "Bike Mount"],
    material: ["Plastic", "Metal", "Aluminum", "Silicone"],
    condition: ["New", "Used", "Open Box"],
  },
  "ring-lights": {
    brand: [
      "Neewer",
      "Godox",
      "Raleno",
      "Hesha",
      "Melamount",
      "Travor",
      "Kavas",
      "Beike",
    ],
    ring_size: ['6"', '10"', '12"', '18"'],
    power_source: ["USB", "Battery", "AC Adapter"],
    condition: ["New", "Used", "Open Box"],
  },
  converters: {
    converter_type: [
      "OTG",
      "USB-C to 3.5mm",
      "Lightning Adapter",
      "HDMI Adapter",
    ],
    condition: ["New", "Used", "Open Box"],
  },
  "selfie-sticks": {
    connectivity: ["Wired", "Bluetooth"],
    condition: ["New", "Used", "Open Box"],
  },
  "stylus-pens": {
    condition: ["New", "Used", "Open Box"],
  },
  "accessory-smart-watches": {
    condition: ["New", "Used", "Open Box", "Refurbished"],
    connectivity: ["Bluetooth", "Wi-Fi", "Cellular"],
    warranty: ["Yes", "No"],
  },
  "external-memory": {
    memory_type: ["MicroSD", "USB Flash", "External SSD"],
    storage: ["16GB", "32GB", "64GB", "128GB", "256GB", "512GB", "1TB"],
    condition: ["New", "Used", "Open Box"],
  },
  keyboards: {
    keyboard_type: ["Mini Keyboard", "Foldable", "Mechanical", "Membrane"],
    connectivity: ["Bluetooth", "USB", "Wireless Dongle"],
    condition: ["New", "Used", "Open Box"],
  },
  "smartphone-lenses": {
    lens_type: ["Wide Angle", "Macro", "Fish Eye", "Telephoto"],
    condition: ["New", "Used", "Open Box"],
  },
  "app-enabled-gadgets": {
    gadget_type: [
      "Smart Tracker",
      "Smart Controller",
      "Smart Health Device",
      "Smart Remote",
    ],
    platform_support: ["Android", "iOS", "Android & iOS"],
    condition: ["New", "Used", "Open Box"],
    warranty: ["Yes", "No"],
  },
};
