import type { ChipsFieldOptionsMap } from "@/config/chipsOptions/types";

const AREA_UNITS = ["Marla", "Kanal", "Square Feet", "Square Yards"];
const COUNT_1_TO_10 = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10+"];
const FLOOR_LEVELS = [
  "Basement",
  "Ground",
  "1st",
  "2nd",
  "3rd",
  "4th",
  "5th",
  "6th",
  "7th",
  "8th",
  "9th",
  "10th+",
];
const AVAILABILITY = [
  "Immediate",
  "Within 15 Days",
  "Within 1 Month",
  "Custom Date",
];
const FURNISHED_OPTIONS = ["Furnished", "Semi-Furnished", "Unfurnished"];

export const PROPERTY_RENT_FIELD_OPTIONS_BY_SUBCATEGORY: Record<
  string,
  ChipsFieldOptionsMap
> = {
  "rent-houses": {
    type: ["House", "Bungalow", "Villa", "Farm House"],
    bedrooms: ["Studio", ...COUNT_1_TO_10],
    bathrooms: COUNT_1_TO_10,
    floors: COUNT_1_TO_10,
    area_unit: AREA_UNITS,
    furnished: FURNISHED_OPTIONS,
    parking_spaces: ["0", ...COUNT_1_TO_10],
    availability: AVAILABILITY,
    features: [
      "Servant Quarters",
      "Drawing Room",
      "Dining Room",
      "TV Lounge",
      "Store Room",
      "Lawn",
      "Car Parking",
      "Corner",
      "Electricity",
      "Gas",
      "Water Supply",
      "Security",
    ],
  },

  "rent-apartments-flats": {
    type: ["Apartment", "Flat", "Studio", "Penthouse"],
    bedrooms: ["Studio", ...COUNT_1_TO_10],
    bathrooms: COUNT_1_TO_10,
    floor_level: FLOOR_LEVELS,
    furnished: FURNISHED_OPTIONS,
    area_unit: AREA_UNITS,
    availability: AVAILABILITY,
    features: [
      "Lift",
      "Car Parking",
      "Security",
      "Balcony",
      "Generator Backup",
      "Gym",
      "Swimming Pool",
      "Play Area",
      "Waste Disposal",
    ],
  },

  "rent-portions-floors": {
    type: ["Upper Portion", "Lower Portion", "Ground Portion", "Floor"],
    bedrooms: ["Studio", ...COUNT_1_TO_10],
    bathrooms: COUNT_1_TO_10,
    floor_level: FLOOR_LEVELS,
    furnished: FURNISHED_OPTIONS,
    area_unit: AREA_UNITS,
    availability: AVAILABILITY,
    features: [
      "Separate Entrance",
      "TV Lounge",
      "Drawing Room",
      "Car Parking",
      "Electricity",
      "Gas",
      "Water Supply",
      "Security",
    ],
  },

  "rent-rooms": {
    type: ["Single Room", "Shared Room", "Hostel Room", "Bed Space"],
    attached_bath: ["Yes", "No"],
    furnished: FURNISHED_OPTIONS,
    room_capacity: ["1", "2", "3", "4", "5+"],
    availability: AVAILABILITY,
    features: [
      "Wi-Fi",
      "Attached Bath",
      "Air Conditioning",
      "Cupboard",
      "Mess Facility",
      "Laundry",
      "Electricity Included",
      "Gas Included",
      "Security",
    ],
  },

  "rent-shops-offices-commercial-space": {
    type: [
      "Shop",
      "Office",
      "Commercial Floor",
      "Building",
      "Warehouse",
      "Factory",
    ],
    area_unit: AREA_UNITS,
    washrooms: COUNT_1_TO_10,
    furnished: FURNISHED_OPTIONS,
    availability: AVAILABILITY,
    features: [
      "Main Road",
      "Parking",
      "Corner",
      "Elevator",
      "CCTV",
      "Security",
      "Backup Power",
      "Internet",
      "Conference Room",
    ],
  },

  "rent-land-plots": {
    type: [
      "Residential Plot",
      "Commercial Plot",
      "Agricultural Land",
      "Industrial Land",
      "Plot File",
      "Plot Form",
    ],
    area_unit: AREA_UNITS,
    facing: ["Corner", "Main Road", "Park Facing", "Inside Street"],
    possession: ["Ready", "Under Development"],
    availability: AVAILABILITY,
    features: [
      "Boundary Wall",
      "Electricity",
      "Gas",
      "Water Supply",
      "Sewerage",
      "Corner",
      "Main Road",
    ],
  },

  "rent-roommates-paying-guests": {
    accommodation_type: ["Roommate", "Paying Guest", "Hostel Seat", "Flatmate"],
    gender_preference: ["Male", "Female", "Any"],
    room_capacity: ["1", "2", "3", "4", "5+"],
    furnished: FURNISHED_OPTIONS,
    availability: AVAILABILITY,
    features: [
      "Wi-Fi",
      "Meals Included",
      "Utilities Included",
      "Air Conditioning",
      "Attached Bath",
      "Laundry",
      "Security",
      "Parking",
    ],
  },

  "rent-vacation-rentals-guest-houses": {
    property_type: [
      "Guest House",
      "Vacation Home",
      "Apartment",
      "Farm House",
      "Villa",
      "Resort Room",
    ],
    bedrooms: ["Studio", ...COUNT_1_TO_10],
    bathrooms: COUNT_1_TO_10,
    guest_capacity: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10+"],
    minimum_stay: ["1", "2", "3", "4", "5", "6", "7", "10", "14", "30"],
    availability: ["Available Now", "Weekend Only", "Custom Dates"],
    features: [
      "Wi-Fi",
      "Air Conditioning",
      "Kitchen",
      "Parking",
      "Security",
      "Swimming Pool",
      "BBQ Area",
      "Scenic View",
      "Cleaning Service",
    ],
  },
};
