import type { ChipsFieldOptionsMap } from "@/config/chipsOptions/types";

const COMMON_SERVICE_MODE = [
  "On-site",
  "At Client Location",
  "Online",
  "Hybrid",
];
const COMMON_EXPERIENCE = [
  "< 1 Year",
  "1-3 Years",
  "3-5 Years",
  "5-10 Years",
  "10+ Years",
];
const COMMON_AVAILABILITY = ["Weekdays", "Weekends", "24/7", "By Appointment"];
const COMMON_PRICE_TYPE = [
  "Fixed",
  "Hourly",
  "Per Day",
  "Per Project",
  "Negotiable",
];
const YES_NO = ["Yes", "No"];

const COMMON_FEATURES = [
  "Professional Team",
  "Quick Response",
  "Verified",
  "Emergency Service",
  "Satisfaction Guarantee",
];

export const SERVICE_FIELD_OPTIONS_BY_SUBCATEGORY: Record<
  string,
  ChipsFieldOptionsMap
> = {
  "other-services": {
    type: ["Consultancy", "Repair", "Maintenance", "Custom Service", "Other"],
    service_mode: COMMON_SERVICE_MODE,
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: COMMON_PRICE_TYPE,
    urgent_service: YES_NO,
    features: COMMON_FEATURES,
  },
  "car-rental": {
    vehicle_type: ["Car", "SUV", "Van", "Coaster", "Luxury Car", "Pickup"],
    rental_duration: ["Hourly", "Half Day", "Full Day", "Weekly", "Monthly"],
    with_driver: YES_NO,
    service_mode: ["With Pickup", "Self Pickup", "With Driver"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Hour", "Per Day", "Per Week", "Per Month", "Negotiable"],
    urgent_service: YES_NO,
    features: ["AC", "GPS", "Fuel Included", "Chauffeur", "Insurance Covered"],
  },
  "tuition-academic": {
    subject: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Biology",
      "English",
      "Computer Science",
      "Accounts",
      "Economics",
      "Quran",
      "Other",
    ],
    class_level: [
      "Primary",
      "Middle",
      "Matric",
      "Intermediate",
      "O/A Levels",
      "University",
    ],
    teaching_mode: ["Online", "Home Tuition", "Academy"],
    service_mode: ["Online", "At Student Location", "At Tutor Place"],
    experience: COMMON_EXPERIENCE,
    availability: ["Morning", "Afternoon", "Evening", "Weekend"],
    price_type: ["Per Hour", "Per Class", "Monthly"],
    urgent_service: YES_NO,
    features: [
      "Demo Class",
      "Test Preparation",
      "Notes Included",
      "One-on-One",
      "Group Class",
    ],
  },
  "web-development": {
    service_type: [
      "Website Development",
      "Ecommerce",
      "Landing Page",
      "Bug Fixing",
      "SEO",
      "Web App",
    ],
    platform: ["WordPress", "Shopify", "Custom", "Wix", "Webflow", "Other"],
    turnaround: ["1-3 Days", "3-7 Days", "1-2 Weeks", "2-4 Weeks", "Custom"],
    service_mode: ["Online", "Hybrid"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Fixed", "Per Project", "Hourly", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Responsive Design",
      "SEO Friendly",
      "Admin Panel",
      "Payment Gateway",
      "Maintenance",
    ],
  },
  "electronics-computer-repair": {
    device_type: [
      "Laptop",
      "Desktop",
      "Mobile",
      "Printer",
      "TV",
      "CCTV",
      "Other",
    ],
    repair_type: [
      "Hardware",
      "Software",
      "Screen Repair",
      "Data Recovery",
      "Installation",
      "Cleaning",
    ],
    doorstep: YES_NO,
    service_mode: ["In Shop", "At Client Location", "Pickup & Drop"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Inspection Fee", "Fixed", "Hourly", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Genuine Parts", "Warranty", "Same Day Repair", "Pickup & Drop"],
  },
  "travel-visa": {
    service_type: [
      "Visit Visa",
      "Student Visa",
      "Work Visa",
      "Umrah",
      "Ticketing",
      "Tour Package",
    ],
    destination: [
      "UAE",
      "Saudi Arabia",
      "UK",
      "USA",
      "Canada",
      "Turkey",
      "Europe",
      "Other",
    ],
    visa_type: ["Single Entry", "Multiple Entry", "Short Term", "Long Term"],
    service_mode: ["Online", "Office Visit"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Application", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Documentation Help",
      "Interview Prep",
      "Tracking",
      "Fast Processing",
    ],
  },
  "farms-fresh-food": {
    product_type: [
      "Organic Vegetables",
      "Fruits",
      "Meat",
      "Milk",
      "Eggs",
      "Honey",
      "Other",
    ],
    quantity_unit: ["Kg", "Dozen", "Liter", "Pack", "Box"],
    delivery_available: YES_NO,
    service_mode: ["Pickup", "Home Delivery"],
    experience: COMMON_EXPERIENCE,
    availability: ["Daily", "Weekly", "Weekend"],
    price_type: ["Per Kg", "Per Dozen", "Per Pack", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Organic", "Farm Fresh", "Same Day Delivery", "Bulk Supply"],
  },
  "construction-services": {
    service_type: [
      "Grey Structure",
      "Finishing",
      "Renovation",
      "Plumbing",
      "Electrical",
      "Paint",
    ],
    project_type: ["House", "Commercial", "Apartment", "Office", "Factory"],
    material_included: YES_NO,
    service_mode: ["On-site", "Project Based"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Sq Ft", "Fixed", "Per Project", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Labor Included", "Material Included", "Supervision", "Turnkey"],
  },
  "event-services": {
    service_type: [
      "Decoration",
      "Management",
      "DJ",
      "Sound",
      "Lighting",
      "Stage Setup",
    ],
    event_type: [
      "Wedding",
      "Birthday",
      "Corporate",
      "Mehndi",
      "Concert",
      "Other",
    ],
    team_size: ["1-2", "3-5", "6-10", "10+"],
    service_mode: ["On-site"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Package", "Per Event", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Customized Theme",
      "Photography Add-on",
      "Sound & Lights",
      "Catering Add-on",
    ],
  },
  "movers-packers": {
    move_type: [
      "Home Shifting",
      "Office Shifting",
      "Intercity",
      "Local",
      "Storage Move",
    ],
    vehicle_size: ["Suzuki", "Mazda", "Truck", "Container"],
    packing_included: YES_NO,
    service_mode: ["On-site", "Pickup & Drop"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Trip", "Per Km", "Fixed", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Packing Material",
      "Loading/Unloading",
      "Insurance",
      "Tracking",
    ],
  },
  "architecture-interior-design": {
    service_type: [
      "Architecture",
      "Interior Design",
      "3D Design",
      "Landscape",
      "Renovation Design",
    ],
    property_type: ["House", "Apartment", "Office", "Commercial", "Restaurant"],
    drawing_type: ["2D Plan", "3D Model", "Walkthrough", "Elevation", "MEP"],
    service_mode: ["Online", "On-site", "Hybrid"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Sq Ft", "Per Project", "Consultation Fee", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Site Visit",
      "Material Guidance",
      "Execution Support",
      "Revisions Included",
    ],
  },
  "video-photography": {
    service_type: ["Photography", "Videography", "Both"],
    event_type: [
      "Wedding",
      "Birthday",
      "Corporate",
      "Product Shoot",
      "Social Media",
    ],
    deliverables: [
      "Photos",
      "Highlight Video",
      "Full Video",
      "Drone Shots",
      "Edited Album",
    ],
    service_mode: ["On-site", "Studio", "Hybrid"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Event", "Hourly", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Drone", "Cinematic", "Live Streaming", "Same Day Teaser"],
  },
  "camera-installation": {
    camera_type: [
      "CCTV",
      "IP Camera",
      "PTZ",
      "Doorbell Camera",
      "Night Vision",
    ],
    property_type: ["Home", "Office", "Shop", "Warehouse", "Factory"],
    system_size: ["1-4 Cameras", "5-8 Cameras", "9-16 Cameras", "16+ Cameras"],
    warranty: ["No", "3 Months", "6 Months", "1 Year", "2 Years"],
    service_mode: ["On-site"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Camera", "Package", "Installation Fee", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Remote Viewing",
      "Night Vision",
      "Backup System",
      "Maintenance Contract",
    ],
  },
  "renting-services": {
    item_type: [
      "Furniture",
      "Generator",
      "Sound System",
      "Tools",
      "Construction Equipment",
      "Other",
    ],
    rental_duration: ["Hourly", "Daily", "Weekly", "Monthly"],
    delivery_available: YES_NO,
    service_mode: ["Pickup", "Delivery", "Both"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Hour", "Per Day", "Per Week", "Per Month", "Negotiable"],
    urgent_service: YES_NO,
    features: ["With Operator", "Security Deposit", "Delivery", "Pickup"],
  },
  "car-services": {
    service_type: [
      "Car Wash",
      "Detailing",
      "Oil Change",
      "Tuning",
      "Denting/Painting",
      "AC Service",
    ],
    vehicle_type: ["Car", "SUV", "Hatchback", "Sedan", "Van", "4x4"],
    at_home_service: YES_NO,
    service_mode: ["Workshop", "At Home"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Fixed", "Per Service", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Genuine Products",
      "Quick Service",
      "Pickup/Drop",
      "Engine Scan",
    ],
  },
  "catering-restaurent": {
    cuisine: [
      "Pakistani",
      "BBQ",
      "Chinese",
      "Fast Food",
      "Continental",
      "Desserts",
    ],
    event_type: [
      "Wedding",
      "Birthday",
      "Corporate",
      "Dawat",
      "Aqiqah",
      "Other",
    ],
    serving_capacity: ["Up to 25", "26-50", "51-100", "101-300", "300+"],
    service_mode: ["At Venue", "Takeaway", "Delivery"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Plate", "Per Head", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Live BBQ",
      "Waiter Service",
      "Crockery Included",
      "Custom Menu",
    ],
  },
  "tailor-services": {
    service_type: [
      "Stitching",
      "Alteration",
      "Embroidery",
      "Uniform Stitching",
      "Custom Design",
    ],
    gender: ["Men", "Women", "Kids", "All"],
    urgent_delivery: YES_NO,
    service_mode: ["At Shop", "Home Visit"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Suit", "Per Piece", "Fixed", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Pickup/Drop",
      "Measurement Visit",
      "Premium Fabric",
      "Same Day Delivery",
    ],
  },
  "insurance-services": {
    insurance_type: [
      "Health",
      "Life",
      "Vehicle",
      "Property",
      "Travel",
      "Business",
    ],
    coverage_type: [
      "Individual",
      "Family",
      "Corporate",
      "Comprehensive",
      "Third Party",
    ],
    claim_assistance: YES_NO,
    service_mode: ["Online", "In Person", "Hybrid"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: [
      "Consultation",
      "Policy Based",
      "Commission Based",
      "Negotiable",
    ],
    urgent_service: YES_NO,
    features: [
      "Policy Comparison",
      "Claim Support",
      "Quick Issuance",
      "Renewal Reminder",
    ],
  },
  "health-services": {
    service_type: [
      "Doctor Consultation",
      "Nursing",
      "Physiotherapy",
      "Lab Test",
      "Mental Health",
      "Vaccination",
    ],
    specialization: [
      "General Physician",
      "Pediatrics",
      "Gynecology",
      "Orthopedic",
      "Dermatology",
      "Psychology",
      "Cardiology",
      "ENT",
    ],
    consultation_mode: ["Clinic Visit", "Home Visit", "Online"],
    service_mode: ["On-site", "At Client Location", "Online"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Visit", "Per Session", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Licensed",
      "Home Visit",
      "Emergency",
      "Female Staff",
      "Prescription Included",
    ],
  },
  "beauty-spa": {
    service_type: [
      "Facial",
      "Haircut",
      "Makeup",
      "Spa",
      "Manicure/Pedicure",
      "Waxing",
      "Bridal Package",
    ],
    target_gender: ["Women", "Men", "Unisex"],
    home_service: YES_NO,
    service_mode: ["Salon", "Home Service", "Both"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Service", "Package", "Hourly", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Bridal Expert",
      "Organic Products",
      "Female Staff",
      "Home Service",
      "Appointment Booking",
    ],
  },
  "fitness-trainers": {
    training_type: [
      "Weight Loss",
      "Muscle Gain",
      "Yoga",
      "Cardio",
      "CrossFit",
      "Rehab Fitness",
      "Sports Training",
    ],
    trainer_gender: ["Male", "Female", "Any"],
    training_mode: ["Gym", "Home", "Online", "Hybrid"],
    service_mode: ["On-site", "At Client Location", "Online", "Hybrid"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Session", "Monthly", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Diet Plan",
      "Body Assessment",
      "Certified Trainer",
      "Female Trainer",
      "Personalized Plan",
    ],
  },
  "pick-drop": {
    ride_type: [
      "School",
      "Office",
      "Airport",
      "Monthly Route",
      "One Way",
      "Round Trip",
    ],
    vehicle_type: ["Bike", "Car", "Van", "Hiace", "Coaster"],
    service_area: [
      "Within City",
      "Intercity",
      "Airport Route",
      "School Route",
      "Office Route",
    ],
    shift_time: ["Morning", "Afternoon", "Evening", "Night"],
    service_mode: ["On-site", "Pickup & Drop"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Ride", "Daily", "Monthly", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "AC Vehicle",
      "Female Driver",
      "Tracking",
      "Safe Ride",
      "Child Safety",
    ],
  },
  drivers: {
    driver_type: [
      "Personal Driver",
      "Office Driver",
      "Delivery Driver",
      "Heavy Vehicle Driver",
      "Chauffeur",
    ],
    license_type: ["LTV", "HTV", "PSV", "Motorbike", "International"],
    shift_type: ["Full Time", "Part Time", "Day Shift", "Night Shift"],
    service_mode: ["At Client Location", "On-site"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Monthly", "Daily", "Per Shift", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Verified Driver",
      "Background Checked",
      "Own Transport",
      "Immediate Joining",
    ],
  },
  carpool: {
    route_type: [
      "Home to Office",
      "Office to Home",
      "University Route",
      "Intercity",
      "Custom Route",
    ],
    vehicle_type: ["Car", "SUV", "Van"],
    seat_capacity: ["1", "2", "3", "4+"],
    commute_time: ["Morning", "Evening", "Both", "Flexible"],
    service_mode: ["On-site", "Pickup & Drop"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Seat", "Daily", "Monthly", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Fuel Share", "AC Ride", "Ladies Only", "Verified Route"],
  },
  maids: {
    maid_type: [
      "House Maid",
      "Cleaning Maid",
      "Cook + Maid",
      "Live-in Maid",
      "Part-time Maid",
    ],
    duty_type: [
      "Cleaning",
      "Dishwashing",
      "Laundry",
      "Ironing",
      "Child Care",
      "Elder Care",
      "All Housework",
    ],
    accommodation: ["Live-in", "Live-out"],
    shift_type: ["Full Time", "Part Time", "Day", "Night"],
    service_mode: ["At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Monthly", "Weekly", "Per Day", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Verified", "Reference Available", "Trained", "Immediate Join"],
  },
  "other-domestic-help": {
    shift_type: ["Full Time", "Part Time", "Day", "Night"],
    service_mode: ["At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Monthly", "Weekly", "Per Day", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Verified", "Reference Available", "Trained", "Immediate Join"],
  },
  cooks: {
    cuisine: [
      "Pakistani",
      "Chinese",
      "Continental",
      "BBQ",
      "Desi",
      "Diet Meals",
      "Multi Cuisine",
    ],
    meal_type: ["Breakfast", "Lunch", "Dinner", "Snacks", "All Meals"],
    accommodation: ["Live-in", "Live-out"],
    service_mode: ["At Client Location", "At Provider Place"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Monthly", "Per Meal", "Per Event", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Hygienic Cooking",
      "Diet Plan",
      "Family Cooking",
      "Party Orders",
    ],
  },
  babysitters: {
    service_type: [
      "Babysitting",
      "Nanny",
      "Newborn Care",
      "After School Care",
      "Special Needs Care",
    ],
    age_group: ["Newborn", "Infant", "Toddler", "Kids 5+"],
    first_aid: YES_NO,
    service_mode: ["At Client Location", "Live-in", "Live-out"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Hourly", "Daily", "Monthly", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "CPR Trained",
      "Reference Available",
      "Female Staff",
      "Night Care",
    ],
  },
  "nursing-staff": {
    service_type: [
      "Patient Care",
      "Elderly Care",
      "Post-Surgery Care",
      "ICU Support",
      "Home Nursing",
    ],
    qualification: [
      "Nurse",
      "Certified Caregiver",
      "Diploma Nurse",
      "BSN",
      "Other",
    ],
    shift_type: ["Day", "Night", "12 Hours", "24 Hours", "Live-in"],
    service_mode: ["At Client Location", "Hospital Visit"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Shift", "Daily", "Monthly", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Medication Support",
      "Vital Monitoring",
      "Female Staff",
      "Trained Nurse",
    ],
  },
  "other-repair-services": {
    property_type: ["Home", "Office", "Shop", "Warehouse", "Factory"],
    service_mode: ["On-site", "At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Inspection", "Fixed", "Hourly", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Same Day Visit",
      "Tools Included",
      "Warranty",
      "Emergency Support",
    ],
  },
  "ac-services": {
    ac_type: [
      "Split AC",
      "Window AC",
      "Cassette AC",
      "Inverter AC",
      "Central AC",
    ],
    service_type: ["Installation", "Repair", "Gas Refill", "Maintenance"],
    tonnage: ["0.75 Ton", "1 Ton", "1.5 Ton", "2 Ton"],
    gas_refill: YES_NO,
    service_mode: ["On-site", "At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Visit", "Per AC", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Jet Wash", "Leak Test", "Original Parts", "Warranty"],
  },
  "pest-control": {
    pest_type: [
      "Termites",
      "Cockroaches",
      "Bed Bugs",
      "Mosquitoes",
      "Rats",
      "Ants",
      "General",
    ],
    property_type: ["Home", "Office", "Shop", "Warehouse", "Restaurant"],
    treatment_type: ["Spray", "Gel", "Fumigation", "Heat", "Organic"],
    warranty: ["No", "1 Month", "3 Months", "6 Months"],
    service_mode: ["On-site", "At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Visit", "Package", "Per Area", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Eco Friendly", "Child Safe", "Follow-up Visit", "Warranty"],
  },
  carpenters: {
    service_type: [
      "Furniture Repair",
      "Custom Furniture",
      "Door Work",
      "Kitchen Work",
      "Cabinet Work",
      "Polish",
    ],
    work_type: ["Home", "Office", "Shop", "Custom Build", "Repair"],
    material_included: YES_NO,
    service_mode: ["On-site", "At Client Location", "Workshop"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Job", "Per Day", "Per Sq Ft", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Custom Design", "CNC Work", "Polish Included", "Warranty"],
  },
  painters: {
    service_type: [
      "Interior Paint",
      "Exterior Paint",
      "Texture",
      "Polish",
      "Whitewash",
    ],
    paint_type: [
      "Emulsion",
      "Enamel",
      "Weather Shield",
      "Texture",
      "Distemper",
    ],
    property_type: ["Home", "Office", "Shop", "Building", "Warehouse"],
    material_included: YES_NO,
    service_mode: ["On-site", "At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Sq Ft", "Per Job", "Daily", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Color Consultation",
      "Wall Repair",
      "Scaffolding",
      "Material Included",
    ],
  },
  electricians: {
    service_type: [
      "Wiring",
      "Installation",
      "Repair",
      "Panel Work",
      "Generator Setup",
      "UPS Setup",
    ],
    property_type: ["Home", "Office", "Shop", "Industrial"],
    emergency_service: YES_NO,
    service_mode: ["On-site", "At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Visit", "Per Job", "Hourly", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Licensed", "Safety Gear", "Same Day Visit", "Warranty"],
  },
  "deep-cleaning": {
    place_type: [
      "Home",
      "Office",
      "Shop",
      "Warehouse",
      "Apartment",
      "Restaurant",
    ],
    frequency: ["One Time", "Weekly", "Monthly", "Custom"],
    team_size: ["1-2", "3-5", "6-10", "10+"],
    supplies_included: YES_NO,
    service_mode: ["On-site", "At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Visit", "Per Sq Ft", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Sanitization",
      "Steam Cleaning",
      "Eco Products",
      "Equipment Included",
    ],
  },
  "water-tank-cleaning": {
    tank_type: ["Underground", "Overhead", "Plastic", "Concrete", "Steel"],
    tank_size: [
      "Up to 500L",
      "500-1000L",
      "1000-2000L",
      "2000-5000L",
      "5000L+",
    ],
    service_type: [
      "Cleaning",
      "Disinfection",
      "Cleaning + Disinfection",
      "Maintenance",
    ],
    service_mode: ["On-site", "At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Tank", "Per Visit", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Sludge Removal", "Disinfection", "Report", "No Water Waste"],
  },
  plumbers: {
    service_type: [
      "Leakage Fix",
      "Pipe Installation",
      "Drain Cleaning",
      "Fitting",
      "Motor Installation",
      "Bathroom Work",
    ],
    property_type: ["Home", "Office", "Shop", "Industrial"],
    emergency_service: YES_NO,
    service_mode: ["On-site", "At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Visit", "Per Job", "Hourly", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Tools Included", "Emergency Visit", "Same Day Fix", "Warranty"],
  },
  "geyser-services": {
    geyser_type: ["Electric", "Gas", "Instant", "Storage", "Solar"],
    service_type: ["Installation", "Repair", "Maintenance", "Replacement"],
    capacity: ["10L", "15L", "25L", "35L+"],
    parts_included: YES_NO,
    service_mode: ["On-site", "At Client Location"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Visit", "Per Job", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Safety Check",
      "Thermostat Fix",
      "Same Day Service",
      "Warranty",
    ],
  },
};
