import type { ChipsFieldOptionsMap } from "@/config/chipsOptions/types";

const COMMON_SERVICE_MODE = [
  "On-site",
  "At Client Location",
  "Online",
  "Hybrid",
];
const COMMON_EXPERIENCE = [
  "< 1 Year",
  "1-3 Years",
  "3-5 Years",
  "5-10 Years",
  "10+ Years",
];
const COMMON_AVAILABILITY = ["Weekdays", "Weekends", "24/7", "By Appointment"];
const COMMON_PRICE_TYPE = [
  "Fixed",
  "Hourly",
  "Per Day",
  "Per Project",
  "Negotiable",
];
const YES_NO = ["Yes", "No"];

const COMMON_FEATURES = [
  "Professional Team",
  "Quick Response",
  "Verified",
  "Emergency Service",
  "Satisfaction Guarantee",
];

export const SERVICE_FIELD_OPTIONS_BY_SUBCATEGORY: Record<
  string,
  ChipsFieldOptionsMap
> = {
  "other-services": {
    type: ["Consultancy", "Repair", "Maintenance", "Custom Service", "Other"],
    service_mode: COMMON_SERVICE_MODE,
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: COMMON_PRICE_TYPE,
    urgent_service: YES_NO,
    features: COMMON_FEATURES,
  },
  "car-rental": {
    vehicle_type: ["Car", "SUV", "Van", "Coaster", "Luxury Car", "Pickup"],
    rental_duration: ["Hourly", "Half Day", "Full Day", "Weekly", "Monthly"],
    with_driver: YES_NO,
    service_mode: ["With Pickup", "Self Pickup", "With Driver"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Hour", "Per Day", "Per Week", "Per Month", "Negotiable"],
    urgent_service: YES_NO,
    features: ["AC", "GPS", "Fuel Included", "Chauffeur", "Insurance Covered"],
  },
  "tuition-academic": {
    subject: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Biology",
      "English",
      "Computer Science",
      "Accounts",
      "Economics",
      "Quran",
      "Other",
    ],
    class_level: [
      "Primary",
      "Middle",
      "Matric",
      "Intermediate",
      "O/A Levels",
      "University",
    ],
    teaching_mode: ["Online", "Home Tuition", "Academy"],
    service_mode: ["Online", "At Student Location", "At Tutor Place"],
    experience: COMMON_EXPERIENCE,
    availability: ["Morning", "Afternoon", "Evening", "Weekend"],
    price_type: ["Per Hour", "Per Class", "Monthly"],
    urgent_service: YES_NO,
    features: [
      "Demo Class",
      "Test Preparation",
      "Notes Included",
      "One-on-One",
      "Group Class",
    ],
  },
  "web-development": {
    service_type: [
      "Website Development",
      "Ecommerce",
      "Landing Page",
      "Bug Fixing",
      "SEO",
      "Web App",
    ],
    platform: ["WordPress", "Shopify", "Custom", "Wix", "Webflow", "Other"],
    turnaround: ["1-3 Days", "3-7 Days", "1-2 Weeks", "2-4 Weeks", "Custom"],
    service_mode: ["Online", "Hybrid"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Fixed", "Per Project", "Hourly", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Responsive Design",
      "SEO Friendly",
      "Admin Panel",
      "Payment Gateway",
      "Maintenance",
    ],
  },
  "electronics-computer-repair": {
    device_type: [
      "Laptop",
      "Desktop",
      "Mobile",
      "Printer",
      "TV",
      "CCTV",
      "Other",
    ],
    repair_type: [
      "Hardware",
      "Software",
      "Screen Repair",
      "Data Recovery",
      "Installation",
      "Cleaning",
    ],
    doorstep: YES_NO,
    service_mode: ["In Shop", "At Client Location", "Pickup & Drop"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Inspection Fee", "Fixed", "Hourly", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Genuine Parts", "Warranty", "Same Day Repair", "Pickup & Drop"],
  },
  "travel-visa": {
    service_type: [
      "Visit Visa",
      "Student Visa",
      "Work Visa",
      "Umrah",
      "Ticketing",
      "Tour Package",
    ],
    destination: [
      "UAE",
      "Saudi Arabia",
      "UK",
      "USA",
      "Canada",
      "Turkey",
      "Europe",
      "Other",
    ],
    visa_type: ["Single Entry", "Multiple Entry", "Short Term", "Long Term"],
    service_mode: ["Online", "Office Visit"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Application", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Documentation Help",
      "Interview Prep",
      "Tracking",
      "Fast Processing",
    ],
  },
  "farms-fresh-food": {
    product_type: [
      "Organic Vegetables",
      "Fruits",
      "Meat",
      "Milk",
      "Eggs",
      "Honey",
      "Other",
    ],
    quantity_unit: ["Kg", "Dozen", "Liter", "Pack", "Box"],
    delivery_available: YES_NO,
    service_mode: ["Pickup", "Home Delivery"],
    experience: COMMON_EXPERIENCE,
    availability: ["Daily", "Weekly", "Weekend"],
    price_type: ["Per Kg", "Per Dozen", "Per Pack", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Organic", "Farm Fresh", "Same Day Delivery", "Bulk Supply"],
  },
  "construction-services": {
    service_type: [
      "Grey Structure",
      "Finishing",
      "Renovation",
      "Plumbing",
      "Electrical",
      "Paint",
    ],
    project_type: ["House", "Commercial", "Apartment", "Office", "Factory"],
    material_included: YES_NO,
    service_mode: ["On-site", "Project Based"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Sq Ft", "Fixed", "Per Project", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Labor Included", "Material Included", "Supervision", "Turnkey"],
  },
  "event-services": {
    service_type: [
      "Decoration",
      "Management",
      "DJ",
      "Sound",
      "Lighting",
      "Stage Setup",
    ],
    event_type: [
      "Wedding",
      "Birthday",
      "Corporate",
      "Mehndi",
      "Concert",
      "Other",
    ],
    team_size: ["1-2", "3-5", "6-10", "10+"],
    service_mode: ["On-site"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Package", "Per Event", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Customized Theme",
      "Photography Add-on",
      "Sound & Lights",
      "Catering Add-on",
    ],
  },
  "movers-packers": {
    move_type: [
      "Home Shifting",
      "Office Shifting",
      "Intercity",
      "Local",
      "Storage Move",
    ],
    vehicle_size: ["Suzuki", "Mazda", "Truck", "Container"],
    packing_included: YES_NO,
    service_mode: ["On-site", "Pickup & Drop"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Trip", "Per Km", "Fixed", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Packing Material",
      "Loading/Unloading",
      "Insurance",
      "Tracking",
    ],
  },
  "architecture-interior-design": {
    service_type: [
      "Architecture",
      "Interior Design",
      "3D Design",
      "Landscape",
      "Renovation Design",
    ],
    property_type: ["House", "Apartment", "Office", "Commercial", "Restaurant"],
    drawing_type: ["2D Plan", "3D Model", "Walkthrough", "Elevation", "MEP"],
    service_mode: ["Online", "On-site", "Hybrid"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Sq Ft", "Per Project", "Consultation Fee", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Site Visit",
      "Material Guidance",
      "Execution Support",
      "Revisions Included",
    ],
  },
  "video-photography": {
    service_type: ["Photography", "Videography", "Both"],
    event_type: [
      "Wedding",
      "Birthday",
      "Corporate",
      "Product Shoot",
      "Social Media",
    ],
    deliverables: [
      "Photos",
      "Highlight Video",
      "Full Video",
      "Drone Shots",
      "Edited Album",
    ],
    service_mode: ["On-site", "Studio", "Hybrid"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Event", "Hourly", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: ["Drone", "Cinematic", "Live Streaming", "Same Day Teaser"],
  },
  "camera-installation": {
    camera_type: [
      "CCTV",
      "IP Camera",
      "PTZ",
      "Doorbell Camera",
      "Night Vision",
    ],
    property_type: ["Home", "Office", "Shop", "Warehouse", "Factory"],
    system_size: ["1-4 Cameras", "5-8 Cameras", "9-16 Cameras", "16+ Cameras"],
    warranty: ["No", "3 Months", "6 Months", "1 Year", "2 Years"],
    service_mode: ["On-site"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Camera", "Package", "Installation Fee", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Remote Viewing",
      "Night Vision",
      "Backup System",
      "Maintenance Contract",
    ],
  },
  "renting-services": {
    item_type: [
      "Furniture",
      "Generator",
      "Sound System",
      "Tools",
      "Construction Equipment",
      "Other",
    ],
    rental_duration: ["Hourly", "Daily", "Weekly", "Monthly"],
    delivery_available: YES_NO,
    service_mode: ["Pickup", "Delivery", "Both"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Hour", "Per Day", "Per Week", "Per Month", "Negotiable"],
    urgent_service: YES_NO,
    features: ["With Operator", "Security Deposit", "Delivery", "Pickup"],
  },
  "car-services": {
    service_type: [
      "Car Wash",
      "Detailing",
      "Oil Change",
      "Tuning",
      "Denting/Painting",
      "AC Service",
    ],
    vehicle_type: ["Car", "SUV", "Hatchback", "Sedan", "Van", "4x4"],
    at_home_service: YES_NO,
    service_mode: ["Workshop", "At Home"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Fixed", "Per Service", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Genuine Products",
      "Quick Service",
      "Pickup/Drop",
      "Engine Scan",
    ],
  },
  "catering-restaurent": {
    cuisine: [
      "Pakistani",
      "BBQ",
      "Chinese",
      "Fast Food",
      "Continental",
      "Desserts",
    ],
    event_type: [
      "Wedding",
      "Birthday",
      "Corporate",
      "Dawat",
      "Aqiqah",
      "Other",
    ],
    serving_capacity: ["Up to 25", "26-50", "51-100", "101-300", "300+"],
    service_mode: ["At Venue", "Takeaway", "Delivery"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Plate", "Per Head", "Package", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Live BBQ",
      "Waiter Service",
      "Crockery Included",
      "Custom Menu",
    ],
  },
  "tailor-services": {
    service_type: [
      "Stitching",
      "Alteration",
      "Embroidery",
      "Uniform Stitching",
      "Custom Design",
    ],
    gender: ["Men", "Women", "Kids", "All"],
    urgent_delivery: YES_NO,
    service_mode: ["At Shop", "Home Visit"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: ["Per Suit", "Per Piece", "Fixed", "Negotiable"],
    urgent_service: YES_NO,
    features: [
      "Pickup/Drop",
      "Measurement Visit",
      "Premium Fabric",
      "Same Day Delivery",
    ],
  },
  "insurance-services": {
    insurance_type: [
      "Health",
      "Life",
      "Vehicle",
      "Property",
      "Travel",
      "Business",
    ],
    coverage_type: [
      "Individual",
      "Family",
      "Corporate",
      "Comprehensive",
      "Third Party",
    ],
    claim_assistance: YES_NO,
    service_mode: ["Online", "In Person", "Hybrid"],
    experience: COMMON_EXPERIENCE,
    availability: COMMON_AVAILABILITY,
    price_type: [
      "Consultation",
      "Policy Based",
      "Commission Based",
      "Negotiable",
    ],
    urgent_service: YES_NO,
    features: [
      "Policy Comparison",
      "Claim Support",
      "Quick Issuance",
      "Renewal Reminder",
    ],
  },
};
