import type { ChipsFieldOptionsMap } from "@/config/chipsOptions/types";

export const VEHICLE_FIELD_OPTIONS_BY_SUBCATEGORY: Record<
  string,
  ChipsFieldOptionsMap
> = {
  cars: {
    fuel: ["Petrol", "Diesel", "CNG", "Petrol/CNG", "Hybrid", "Electric"],
    body_type: [
      "Sedan",
      "SUV",
      "Hatchback",
      "Coupe",
      "Convertible",
      "Wagon",
      "MPV",
      "Pickup",
      "Van",
    ],
    color: [
      "White",
      "Black",
      "Gray",
      "Silver",
      "Blue",
      "Red",
      "Brown",
      "Gold",
      "Green",
      "Yellow",
      "Maroon",
    ],
    registration_city: [
      "Islamabad",
      "Karachi",
      "Lahore",
      "Rawalpindi",
      "Multan",
      "Peshawar",
      "Quetta",
      "Faisalabad",
      "Gujranwala",
      "Sialkot",
      "Sargodha",
      "Bahawalpur",
      "Hyderabad",
      "Sukkur",
      "Abbottabad",
      "Mardan",
      "Jhelum",
      "Chakwal",
      "Kohat",
      "Other",
    ],
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Sunroof",
      "Leather Seats",
      "Alloy Wheels",
      "Central Locking",
      "ABS",
      "Airbags",
      "Cruise Control",
      "Navigation",
      "Bluetooth",
      "Rear Camera",
      "Parking Sensors",
    ],
    condition: ["New", "Used", "Certified", "Imported"],
    transmission: ["Automatic", "Manual", "CVT"],
    documents: [
      "Original Book",
      "Smart Card",
      "Token Paid",
      "Transfer Letter",
      "File Available",
      "Duplicate Documents",
    ],
    assembly: ["Local", "Imported"],
    registered: ["Yes", "No"],
  },
  "cars-on-installments": {
    fuel: ["Petrol", "Diesel", "CNG", "Petrol/CNG", "Hybrid", "Electric"],
    body_type: ["Sedan", "SUV", "Hatchback", "Coupe", "Wagon", "MPV", "Pickup"],
    color: ["White", "Black", "Gray", "Silver", "Blue", "Red", "Brown"],
    registration_city: [
      "Islamabad",
      "Karachi",
      "Lahore",
      "Rawalpindi",
      "Faisalabad",
      "Multan",
      "Peshawar",
      "Quetta",
      "Hyderabad",
      "Gujranwala",
      "Other",
    ],
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Alloy Wheels",
      "ABS",
      "Airbags",
      "Cruise Control",
      "Rear Camera",
      "Bluetooth",
    ],
    condition: ["New", "Used", "Certified", "Imported"],
    transmission: ["Automatic", "Manual", "CVT"],
    registered: ["Yes", "No"],
    documents: ["Original Book", "Smart Card", "Token Paid", "File Available"],
    assembly: ["Local", "Imported"],
  },
  "buses-vans-trucks": {
    condition: ["New", "Used", "Refurbished"],
  },
  "rickshaw-chingchi": {
    condition: ["New", "Used", "Refurbished"],
  },
  "tractors-trailers": {
    condition: ["New", "Used", "Refurbished"],
  },
  "other-vehicles": {
    condition: ["New", "Used", "Refurbished"],
  },
  boats: {
    condition: ["New", "Used", "Refurbished"],
  },
};
