import type { ChipsFieldOptionsMap } from "@/config/chipsOptions/types";

export const VEHICLES_ACCESSORIES_FIELD_OPTIONS_BY_SUBCATEGORY: Record<
  string,
  ChipsFieldOptionsMap
> = {
  // Cars Accessories
  interior: {
    accessory_type: [
      "Floor Mats",
      "Seat Covers",
      "Steering Wheel Cover",
      "Dashboard Mat",
      "Door Sills",
      "Pedal Covers",
      "Arm Rests",
      "Cup Holders",
    ],
    brand: [
      "Bosch",
      "Valeo",
      "Continental",
      "Delphi",
      "Denso",
      "Hella",
      "Magna",
      "Yazaki",
    ],
    condition: ["New", "Used", "Like New"],
  },
  exterior: {
    accessory_type: [
      "Body Kit",
      "Spoiler",
      "Side Steps",
      "Roof Rack",
      "Bumper Guard",
      "Side Mirror Cover",
      "Door Edge Guards",
      "Fender Trim",
    ],
    material: [
      "Plastic",
      "Metal",
      "Aluminum",
      "Stainless Steel",
      "Carbon Fiber",
    ],
    condition: ["New", "Used", "Like New"],
  },
  "tools-gadgets": {
    tool_type: [
      "Jump Starter",
      "Air Compressor",
      "Tool Kit",
      "Battery Charger",
      "OBD Scanner",
      "Tire Gauge",
      "Jumper Cables",
      "Jack",
    ],
    condition: ["New", "Used", "Like New"],
  },
  "audio-multimedia": {
    product_type: [
      "Car Stereo",
      "Speakers",
      "Amplifier",
      "Subwoofer",
      "Equalizer",
      "Bluetooth Speaker",
      "Dashboard Camera",
    ],
    brand: [
      "Sony",
      "Alpine",
      "Kenwood",
      "Pioneer",
      "JBL",
      "Bose",
      "Harman Kardon",
      "Infinity",
    ],
    connectivity: ["Bluetooth", "USB", "3.5mm", "RCA", "WiFi"],
    condition: ["New", "Used", "Open Box"],
  },
  "safety-security": {
    product_type: [
      "Dash Cam",
      "CCTV Camera",
      "Alarm System",
      "GPS Tracker",
      "Child Lock",
      "Anti-Theft Device",
      "Speed Camera Detector",
    ],
    brand: [
      "Blackvue",
      "70mai",
      "Viofo",
      "Vantrue",
      "Thinkware",
      "Cobra",
      "Kenwood",
      "Pioneer",
    ],
    condition: ["New", "Used", "Like New"],
  },
  "paints-primers-tools": {
    product_type: [
      "Car Paint",
      "Primer",
      "Spray Gun",
      "Sanding Block",
      "Paint Brush",
      "Masking Tape",
      "Drop Cloth",
    ],
    brand: [
      "Nippon Paint",
      "Asian Paints",
      "PPG",
      "Basf",
      "Mekka",
      "Bosch",
      "Makita",
      "Stanley",
    ],
    condition: ["New", "Used", "Open Box"],
  },

  // Spare Parts
  "spark-plugs": {
    type: ["Standard", "Iridium", "Platinum", "Copper"],
    brand: [
      "Bosch",
      "Denso",
      "Champion",
      "NGK",
      "Autolite",
      "Niehoff",
      "Power Wagon",
      "Mobiletron",
    ],
    condition: ["New", "Used"],
  },
  "air-filters": {
    filter_type: ["Paper", "Cotton", "Foam", "Mesh"],
    brand: [
      "Bosch",
      "Denso",
      "Mann Filter",
      "Sakura",
      "Delphi",
      "Fram",
      "Mahle",
      "Valeo",
    ],
    condition: ["New", "Used"],
  },
  "cabin-filters": {
    brand: [
      "Bosch",
      "Denso",
      "Mann Filter",
      "Fram",
      "Sakura",
      "Delphi",
      "Mahle",
      "Valeo",
    ],
    condition: ["New", "Used"],
  },
  "timing-belt": {
    brand: [
      "Bosch",
      "Denso",
      "Delphi",
      "Valeo",
      "Continental",
      "Dayco",
      "Gates",
      "Bando",
    ],
    condition: ["New", "Used"],
  },
  "water-pumps": {
    brand: [
      "Bosch",
      "Denso",
      "Delphi",
      "Valeo",
      "Toyota",
      "Honda",
      "Hyundai",
      "Maruti",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  "fuel-filters": {
    filter_type: ["Spin-on", "Cartridge", "Inline"],
    brand: [
      "Bosch",
      "Denso",
      "Delphi",
      "Sakura",
      "Fram",
      "Mann Filter",
      "Valeo",
      "Mahle",
    ],
    condition: ["New", "Used"],
  },
  "oil-filters": {
    brand: [
      "Bosch",
      "Denso",
      "Fram",
      "Mann Filter",
      "Mahle",
      "AC Delco",
      "Sakura",
      "Valeo",
    ],
    condition: ["New", "Used"],
  },
  "brake-pads": {
    material: ["Organic", "Metallic", "Ceramic", "Semi-Metallic"],
    brand: [
      "Bosch",
      "Denso",
      "Delphi",
      "Brembo",
      "TRW",
      "Akebono",
      "Jurid",
      "Ferodo",
    ],
    condition: ["New", "Used"],
  },
  "brake-discs": {
    brand: [
      "Bosch",
      "Brembo",
      "TRW",
      "Delphi",
      "Akebono",
      "EBC",
      "Ferodo",
      "Coated",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  "brake-calipers": {
    brand: [
      "Bosch",
      "Delphi",
      "TRW",
      "Brembo",
      "Akebono",
      "Sumitomo",
      "Nissin",
      "Tokico",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  "shock-absorbers": {
    brand: [
      "Bosch",
      "Denso",
      "Delphi",
      "Bilstein",
      "KYB",
      "Koni",
      "Gabriel",
      "Monroe",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  springs: {
    brand: [
      "Bosch",
      "Delphi",
      "Bilstein",
      "Eibach",
      "H&R",
      "Intrax",
      "King",
      "Pedders",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  "ball-joints": {
    brand: [
      "Bosch",
      "Delphi",
      "TRW",
      "Moog",
      "LEMFORDER",
      "Showa",
      "Mobis",
      "Valeo",
    ],
    condition: ["New", "Used"],
  },
  struts: {
    brand: [
      "Bosch",
      "Delphi",
      "Bilstein",
      "KYB",
      "Koni",
      "Monroe",
      "Gabriel",
      "Tokico",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  radiator: {
    brand: [
      "Bosch",
      "Denso",
      "Delphi",
      "Valeo",
      "Behr",
      "Luzar",
      "Orion",
      "Modine",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  "coolant-hoses": {
    brand: [
      "Bosch",
      "Delphi",
      "Valeo",
      "Molded",
      "OEM",
      "Continental",
      "Dayco",
      "Bando",
    ],
    condition: ["New", "Used"],
  },
  alternator: {
    brand: [
      "Bosch",
      "Denso",
      "Delphi",
      "Valeo",
      "Hitachi",
      "Motorcraft",
      "Remy International",
      "Leece Neville",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  "starter-motor": {
    brand: [
      "Bosch",
      "Denso",
      "Delphi",
      "Valeo",
      "Hitachi",
      "Motorcraft",
      "Remy International",
      "Leece Neville",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  batteries: {
    capacity: ["40Ah", "50Ah", "60Ah", "70Ah", "80Ah", "100Ah"],
    brand: [
      "Amaron",
      "Exide",
      "Bosch",
      "Varta",
      "AC Delco",
      "Duracell",
      "Okaya",
      "Luminous",
    ],
    voltage: ["12V", "24V", "6V"],
    origin: ["Original", "Compatible", "Refurbished"],
    warranty: ["3 Months", "6 Months", "1 Year", "2 Years"],
    condition: ["New", "Used"],
  },
  "car-lights": {
    light_type: [
      "Headlight",
      "Tail Light",
      "Fog Light",
      "Turn Signal",
      "Interior Light",
      "Brake Light",
    ],
    brand: [
      "Bosch",
      "Hella",
      "Philips",
      "Osram",
      "GE",
      "Sylvania",
      "NRG",
      "Narva",
    ],
    condition: ["New", "Used"],
  },
  "windshield-glass": {
    glass_type: ["Windshield", "Side Window", "Rear Window", "Door Glass"],
    condition: ["New", "Used"],
  },
  "seat-upholstery": {
    material: ["Fabric", "Leather", "Synthetic Leather", "Suede", "Velvet"],
    seat_type: ["Front", "Rear", "Full Set"],
    condition: ["New", "Used"],
  },
  "door-locks": {
    lock_type: ["Electronic", "Manual", "Smart Lock"],
    brand: [
      "Bosch",
      "Delphi",
      "Valeo",
      "Continental",
      "Motorcraft",
      "OEM",
      "Latch Assemblies",
      "Electric Locks",
    ],
    condition: ["New", "Used"],
  },
  "door-handles": {
    brand: [
      "OEM",
      "Replacement",
      "Chrome",
      "Black",
      "Motorcraft",
      "Delphi",
      "Valeo",
      "Continental",
    ],
    condition: ["New", "Used"],
  },
  "transmission-parts": {
    part_type: ["Gasket", "Seal", "Valve", "Gear", "Filter"],
    condition: ["New", "Used"],
  },
  "engine-gaskets": {
    brand: [
      "Bosch",
      "Delphi",
      "Valeo",
      "Fel-Pro",
      "Victor Reinz",
      "OEM",
      "Metal",
      "Rubber Combined",
    ],
    condition: ["New", "Used"],
  },
  "wiper-blades": {
    condition: ["New", "Used"],
  },
  "clutch-plate": {
    brand: [
      "Bosch",
      "Delphi",
      "Valeo",
      "Sachs",
      "LuK",
      "Exedy",
      "Aisin",
      "Jtekt",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  "fuel-pumps": {
    brand: [
      "Bosch",
      "Denso",
      "Delphi",
      "Walbro",
      "Airtex",
      "Carter",
      "AC Delco",
      "Motorcraft",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  "fuel-injectors": {
    brand: [
      "Bosch",
      "Denso",
      "Delphi",
      "InfinityMechanics",
      "Flow Match",
      "Siemens",
      "Misubishi",
      "Hitachi",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  "exhaust-muffler": {
    material: ["Stainless Steel", "Aluminized Steel", "Titanium"],
    brand: [
      "Bosch",
      "Delphi",
      "Eberspacher",
      "Tenneco",
      "Flowmaster",
      "Magnaflow",
      "Borla",
      "Custom",
    ],
    condition: ["New", "Used"],
  },
  "catalytic-converter": {
    brand: [
      "Bosch",
      "Delphi",
      "Eberspacher",
      "Tenneco",
      "Magnaflow",
      "OEM",
      "Vibrant",
      "Direct Fit",
    ],
    condition: ["New", "Used", "Refurbished"],
  },
  "door-panels": {
    material: ["Plastic", "Leather", "Fabric", "Carbon Fiber"],
    condition: ["New", "Used"],
  },
  mirrors: {
    mirror_type: ["Side Mirror", "Rear View Mirror", "Blind Spot Mirror"],
    condition: ["New", "Used"],
  },
  "other-spare-parts": {
    condition: ["New", "Used", "Refurbished"],
  },

  // Car Care
  covers: {
    cover_type: ["Full Car Cover", "Half Car Cover", "Soft Top", "Hard Top"],
    material: ["Polyester", "Cotton", "Waterproof Fabric", "Fleece Lined"],
    size: ["Small", "Medium", "Large", "Extra Large"],
    condition: ["New", "Used"],
  },
  cleaners: {
    cleaner_type: [
      "Exterior Cleaner",
      "Interior Cleaner",
      "Glass Cleaner",
      "Leather Cleaner",
      "Plastic Cleaner",
      "Wheel Cleaner",
    ],
    brand: [
      "WD-40",
      "Castrol",
      "Shell",
      "Valvoline",
      "3M",
      "Liqui Moly",
      "Zep",
      "Armor All",
    ],
    origin: ["Original", "Compatible"],
    condition: ["New", "Used"],
  },
  "air-fresheners": {
    scent: [
      "Vanilla",
      "Lavender",
      "Citrus",
      "Ocean",
      "Cherry",
      "Pine",
      "Musk",
      "Floral",
    ],
    brand: [
      "Armor All",
      "Febreze",
      "Airwick",
      "Yankee Candle",
      "Little Trees",
      "Xtreme",
      "Abro",
      "Car Mates",
    ],
    condition: ["New", "Used"],
  },
  "microfiber-cloths": {
    color: ["Blue", "Red", "Green", "Yellow", "Gray", "Black", "White"],
    condition: ["New", "Used"],
  },
  "pressure-washers": {
    condition: ["New", "Used"],
  },
  polishes: {
    type: ["Fine Polish", "Medium Polish", "Heavy Polish", "Rubbing Compound"],
    brand: [
      "Turtle Wax",
      "Meguiar's",
      "Armor All",
      "3M",
      "Mothers",
      "Griot's Garage",
      "Sonax",
      "Chemical Guys",
    ],
    origin: ["Original", "Compatible"],
    condition: ["New", "Used"],
  },
  waxes: {
    type: [
      "Paste Wax",
      "Liquid Wax",
      "Spray Wax",
      "Synthetic Wax",
      "Carnauba Wax",
    ],
    brand: [
      "Turtle Wax",
      "Meguiar's",
      "Armor All",
      "3M",
      "Mothers",
      "Griot's Garage",
      "Sonax",
      "Chemical Guys",
    ],
    origin: ["Original", "Compatible"],
    condition: ["New", "Used"],
  },
  shampoos: {
    shampoo_type: ["Regular Shampoo", "pH Neutral", "Foam Wash", "Waterless"],
    brand: [
      "Turtle Wax",
      "Meguiar's",
      "Armor All",
      "3M",
      "Chemical Guys",
      "Carpro",
      "Optimum",
      "Detail King",
    ],
    origin: ["Original", "Compatible"],
    condition: ["New", "Used"],
  },
  "compound-polishes": {
    brand: [
      "Turtle Wax",
      "Meguiar's",
      "3M",
      "Mothers",
      "Griot's Garage",
      "Sonax",
      "Chemical Guys",
      "Carpro",
    ],
    condition: ["New", "Used"],
  },
  "pads-sponges-brushes": {
    product_type: [
      "Polishing Pad",
      "Cleaning Sponge",
      "Washing Brush",
      "Detail Brush",
    ],
    condition: ["New", "Used"],
  },
  "car-care-other": {
    brand: [
      "Turtle Wax",
      "Armor All",
      "Meguiar's",
      "3M",
      "WD-40",
      "Chemical Guys",
      "Detail King",
      "Carpro",
    ],
    condition: ["New", "Used"],
  },

  // Oil & Lubricants
  "engine-oil": {
    viscosity: [
      "0W-20",
      "0W-30",
      "0W-40",
      "5W-20",
      "5W-30",
      "5W-40",
      "10W-30",
      "10W-40",
      "15W-40",
      "20W-50",
    ],
    brand: [
      "Mobil",
      "Shell",
      "Castrol",
      "Valvoline",
      "Bardahl",
      "Fuchs",
      "Total",
      "Caltex",
    ],
    quantity: ["1L", "4L", "5L", "10L", "20L"],
    type: ["Mineral", "Semi-Synthetic", "Fully Synthetic"],
    origin: ["Original", "Compatible", "Duplicate"],
    condition: ["New", "Unopened"],
  },
  "gear-oil": {
    brand: [
      "Mobil",
      "Shell",
      "Castrol",
      "Valvoline",
      "Bardahl",
      "Fuchs",
      "Total",
      "Caltex",
    ],
    viscosity: ["75W-90", "80W-90", "85W-140"],
    quantity: ["1L", "4L", "5L", "10L"],
  },
  coolants: {
    brand: [
      "Mobil",
      "Shell",
      "Castrol",
      "Valvoline",
      "Bardahl",
      "Fuchs",
      "Motul",
      "Pentosin",
    ],
    coolant_type: ["Green", "Pink", "Orange", "Blue", "Yellow"],
    quantity: ["1L", "4L", "5L", "10L"],
  },
  "chain-lubes-cleaners": {
    product_type: ["Chain Lube", "Chain Cleaner", "Combination"],
  },
  "multipurpose-grease": {
    quantity: ["100g", "500g", "1kg", "5kg"],
  },
  "brake-oil": {
    brand: [
      "Mobil",
      "Shell",
      "Castrol",
      "Valvoline",
      "ATE",
      "Bosch",
      "DOT 3",
      "DOT 4",
    ],
    dot_type: ["DOT 3", "DOT 4", "DOT 5", "DOT 5.1"],
    origin: ["Original", "Compatible"],
    quantity: ["1L", "5L"],
    condition: ["New", "Unopened"],
  },
  "fluids-flushes": {
    fluid_type: [
      "Brake Fluid",
      "Power Steering Fluid",
      "Transmission Fluid",
      "Coolant Flush",
      "Fuel System Flush",
    ],
  },
  "oil-additives": {
    brand: [
      "Bardahl",
      "Redline",
      "Liqui Moly",
      "Castrol",
      "Motul",
      "STP",
      "Millers Oils",
      "Gunk",
    ],
    additive_type: [
      "Engine Protectant",
      "Fuel Additive",
      "Cooling System Additive",
      "Oil Booster",
    ],
    origin: ["Original", "Compatible"],
    condition: ["New", "Unopened"],
  },
  "fuel-additives": {
    brand: [
      "Bardahl",
      "Redline",
      "Liqui Moly",
      "STP",
      "Gunk",
      "Techron",
      "Chevron",
      "Wynn's",
    ],
    additive_type: [
      "Fuel Injector Cleaner",
      "Octane Booster",
      "Fuel Stabilizer",
      "Performance Booster",
    ],
  },
  solvents: {
    solvent_type: [
      "Parts Cleaner",
      "Degreaser",
      "Carburetor Cleaner",
      "Contact Cleaner",
    ],
  },
  "cvtf-oil": {
    brand: [
      "Mobil",
      "Shell",
      "Castrol",
      "Nissan",
      "Honda",
      "Toyota",
      "Hyundai",
      "Suzuki",
    ],
    quantity: ["1L", "4L", "5L"],
  },
  adhesives: {
    adhesive_type: [
      "Gasket Sealant",
      "Thread Locker",
      "Bonding Adhesive",
      "Weatherstrip Adhesive",
    ],
  },
};
