import type { Field } from "@/config/postFields/types";

export const ANIMAL_POST_FIELDS_BY_SUBCATEGORY: Record<string, Field[]> = {
  // Pet Food & Accessories
  "cat-accessories": [
    {
      key: "accessory_type",
      label: "Accessory Type",
      type: "select",
      required: true,
    },
    { key: "brand", label: "Brand", type: "text" },
    { key: "material", label: "Material", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "dog-accessories": [
    {
      key: "accessory_type",
      label: "Accessory Type",
      type: "select",
      required: true,
    },
    { key: "brand", label: "Brand", type: "text" },
    { key: "size", label: "Size", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "beds-mats-houses": [
    { key: "type", label: "Bed Type", type: "chips", required: true },
    { key: "size", label: "Size", type: "chips" },
    { key: "material", label: "Material", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "dog-food": [
    { key: "brand", label: "Brand", type: "select", required: true },
    { key: "type", label: "Food Type", type: "chips", required: true },
    { key: "quantity", label: "Quantity (kg)", type: "text" },
    { key: "age_group", label: "Age Group", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  brooders: [
    { key: "capacity", label: "Capacity", type: "chips", required: true },
    { key: "type", label: "Brooder Type", type: "chips" },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  medicines: [
    {
      key: "medicine_name",
      label: "Medicine Name",
      type: "text",
      required: true,
    },
    { key: "type", label: "Type", type: "chips", required: true },
    { key: "quantity", label: "Quantity", type: "text" },
    { key: "expiry_date", label: "Expiry Date", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "pet-scratchers-furniture": [
    { key: "type", label: "Type", type: "chips", required: true },
    { key: "material", label: "Material", type: "chips" },
    { key: "size", label: "Size", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "cat-toys": [
    { key: "toy_type", label: "Toy Type", type: "chips", required: true },
    { key: "material", label: "Material", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "bowls-feeders": [
    { key: "type", label: "Type", type: "chips", required: true },
    { key: "material", label: "Material", type: "chips" },
    { key: "capacity", label: "Capacity", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "carriers-travel": [
    {
      key: "carrier_type",
      label: "Carrier Type",
      type: "chips",
      required: true,
    },
    { key: "size", label: "Size", type: "chips" },
    { key: "material", label: "Material", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "clothing-shoes-accessories": [
    { key: "item_type", label: "Item Type", type: "chips", required: true },
    { key: "size", label: "Size", type: "chips" },
    { key: "material", label: "Material", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "fish-food": [
    { key: "brand", label: "Brand", type: "select" },
    { key: "type", label: "Food Type", type: "chips", required: true },
    { key: "quantity", label: "Quantity (grams)", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "litter-cleanup-sanitation": [
    {
      key: "product_type",
      label: "Product Type",
      type: "chips",
      required: true,
    },
    { key: "brand", label: "Brand", type: "text" },
    { key: "quantity", label: "Quantity", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "dental-healthcare": [
    {
      key: "product_type",
      label: "Product Type",
      type: "chips",
      required: true,
    },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "dog-toys": [
    { key: "toy_type", label: "Toy Type", type: "chips", required: true },
    { key: "material", label: "Material", type: "chips" },
    { key: "size", label: "Size", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "training-aids": [
    { key: "aid_type", label: "Aid Type", type: "chips", required: true },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  technology: [
    { key: "device_type", label: "Device Type", type: "chips", required: true },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "cages-crates-doors": [
    { key: "cage_type", label: "Cage Type", type: "chips", required: true },
    { key: "size", label: "Size", type: "chips" },
    { key: "material", label: "Material", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "hen-cages": [
    { key: "capacity", label: "Capacity", type: "chips", required: true },
    { key: "size", label: "Size", type: "chips" },
    { key: "material", label: "Material", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  incubators: [
    { key: "capacity", label: "Capacity", type: "chips", required: true },
    { key: "type", label: "Incubator Type", type: "chips" },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  aquariums: [
    {
      key: "size",
      label: "Size (gallons/liters)",
      type: "chips",
      required: true,
    },
    { key: "type", label: "Aquarium Type", type: "chips" },
    { key: "material", label: "Material", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "birds-accessories": [
    {
      key: "accessory_type",
      label: "Accessory Type",
      type: "chips",
      required: true,
    },
    { key: "material", label: "Material", type: "chips" },
    { key: "size", label: "Size", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "other-animal-food-accessories": [
    {
      key: "product_type",
      label: "Product Type",
      type: "text",
      required: true,
    },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "pet-grooming": [
    {
      key: "service_product",
      label: "Service/Product",
      type: "text",
      required: true,
    },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "birds-food": [
    { key: "brand", label: "Brand", type: "select" },
    { key: "type", label: "Food Type", type: "chips", required: true },
    { key: "quantity", label: "Quantity (kg)", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "cat-food": [
    { key: "brand", label: "Brand", type: "select", required: true },
    { key: "type", label: "Food Type", type: "chips", required: true },
    { key: "quantity", label: "Quantity (kg)", type: "text" },
    { key: "age_group", label: "Age Group", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],

  // Livestock
  goats: [
    { key: "breed", label: "Breed", type: "text", required: true },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "gender", label: "Gender", type: "chips", required: true },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  cows: [
    { key: "breed", label: "Breed", type: "text", required: true },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "gender", label: "Gender", type: "chips", required: true },
    { key: "milk_production", label: "Milk Production", type: "text" },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  sheep: [
    { key: "breed", label: "Breed", type: "text", required: true },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "gender", label: "Gender", type: "chips", required: true },
    { key: "wool_quality", label: "Wool Quality", type: "chips" },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  bulls: [
    { key: "breed", label: "Breed", type: "text", required: true },
    { key: "age", label: "Age", type: "text", required: true },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  buffalos: [
    { key: "breed", label: "Breed", type: "text", required: true },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "gender", label: "Gender", type: "chips", required: true },
    { key: "milk_production", label: "Milk Production", type: "text" },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  camels: [
    { key: "breed", label: "Breed", type: "text", required: true },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "gender", label: "Gender", type: "chips", required: true },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  horses: [
    { key: "breed", label: "Breed", type: "text", required: true },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "color", label: "Color", type: "chips" },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  donkeys: [
    { key: "breed", label: "Breed", type: "text" },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "gender", label: "Gender", type: "chips", required: true },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  pigs: [
    { key: "breed", label: "Breed", type: "text", required: true },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "gender", label: "Gender", type: "chips", required: true },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  poultry: [
    { key: "bird_type", label: "Bird Type", type: "chips", required: true },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "quantity", label: "Quantity", type: "text", required: true },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  rabbits: [
    { key: "breed", label: "Breed", type: "text" },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "gender", label: "Gender", type: "chips" },
    { key: "color", label: "Color", type: "chips" },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  alpacas: [
    { key: "breed", label: "Breed", type: "text" },
    { key: "age", label: "Age", type: "text", required: true },
    { key: "gender", label: "Gender", type: "chips", required: true },
    { key: "fiber_quality", label: "Fiber Quality", type: "chips" },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "vaccination_status", label: "Vaccination Status", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  others: [
    { key: "animal_type", label: "Animal Type", type: "text", required: true },
    { key: "breed", label: "Breed", type: "text" },
    { key: "age", label: "Age", type: "text", required: true },
    {
      key: "health_status",
      label: "Health Status",
      type: "chips",
      required: true,
    },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
};
