import type { Field } from "@/config/postFields/types";

export const MOBILE_POST_FIELDS_BY_SUBCATEGORY: Record<string, Field[]> = {
  "mobile-phones": [
    {
      key: "brand_model",
      label: "Brand & Model",
      type: "brand-model",
      required: true,
    },
    {
      key: "condition",
      label: "Condition",
      type: "chips",
      required: true,
    },
    {
      key: "pta_status",
      label: "PTA Status",
      type: "chips",
      required: true,
    },
    {
      key: "storage",
      label: "Storage",
      type: "select",
    },
    {
      key: "ram",
      label: "RAM",
      type: "select",
    },
    {
      key: "battery",
      label: "Battery",
      type: "chips",
    },
    {
      key: "warranty",
      label: "Warranty",
      type: "chips",
    },
    {
      key: "color",
      label: "Color",
      type: "text",
      placeholder: "e.g. Midnight Black",
    },
  ],
  tablets: [
    {
      key: "brand_model",
      label: "Brand & Model",
      type: "brand-model",
      required: true,
    },
    {
      key: "condition",
      label: "Condition",
      type: "chips",
      required: true,
    },
    {
      key: "storage",
      label: "Storage",
      type: "select",
    },
    {
      key: "ram",
      label: "RAM",
      type: "select",
    },
    {
      key: "warranty",
      label: "Warranty",
      type: "chips",
    },
  ],
  "smart-watches": [
    {
      key: "brand_model",
      label: "Brand & Model",
      type: "brand-model",
      required: true,
    },
    {
      key: "condition",
      label: "Condition",
      type: "chips",
      required: true,
    },
    {
      key: "warranty",
      label: "Warranty",
      type: "chips",
    },
  ],
  "landline-phones": [
    {
      key: "brand",
      label: "Brand",
      type: "text",
      required: true,
      placeholder: "e.g. Panasonic, Cisco",
    },
    {
      key: "model",
      label: "Model",
      type: "text",
      placeholder: "e.g. KX-TGC220",
    },
    {
      key: "condition",
      label: "Condition",
      type: "chips",
      required: true,
    },
    {
      key: "warranty",
      label: "Warranty",
      type: "chips",
    },
  ],
  accessories: [
    {
      key: "condition",
      label: "Condition",
      type: "chips",
      required: true,
    },
    {
      key: "compatibility",
      label: "Compatibility",
      type: "text",
      placeholder: "e.g. iPhone 13/14, Type-C devices",
    },
    {
      key: "warranty",
      label: "Warranty",
      type: "chips",
    },
  ],
  earphones: [
    { key: "brand", label: "Brand", type: "select", required: true },
    { key: "type", label: "Type", type: "chips", required: true },
    { key: "connectivity", label: "Connectivity", type: "chips" },
    { key: "origin", label: "Origin", type: "chips", required: true },
    { key: "condition", label: "Condition", type: "chips", required: true },
    { key: "warranty", label: "Warranty", type: "chips" },
  ],
  "covers-cases": [
    {
      key: "brand",
      label: "Brand",
      type: "select",
      placeholder: "e.g. Spigen, Nillkin",
    },
    {
      key: "compatible_model",
      label: "Compatible Model",
      type: "text",
      required: true,
    },
    { key: "case_type", label: "Case Type", type: "chips", required: true },
    { key: "material", label: "Material", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  chargers: [
    { key: "brand", label: "Brand", type: "select", required: true },
    {
      key: "charger_type",
      label: "Charger Type",
      type: "chips",
      required: true,
    },
    {
      key: "connector_type",
      label: "Connector Type",
      type: "select",
      required: true,
    },
    {
      key: "power_output",
      label: "Power Output",
      type: "select",
      required: true,
    },
    { key: "origin", label: "Origin", type: "chips", required: true },
    { key: "condition", label: "Condition", type: "chips", required: true },
    { key: "warranty", label: "Warranty", type: "chips" },
  ],
  "other-accessories": [
    {
      key: "accessory_type",
      label: "Accessory Type",
      type: "text",
      required: true,
    },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
    { key: "compatibility", label: "Compatibility", type: "text" },
    { key: "warranty", label: "Warranty", type: "chips" },
  ],
  headphones: [
    { key: "brand", label: "Brand", type: "select", required: true },
    { key: "type", label: "Type", type: "chips", required: true },
    { key: "connectivity", label: "Connectivity", type: "chips" },
    { key: "origin", label: "Origin", type: "chips", required: true },
    { key: "condition", label: "Condition", type: "chips", required: true },
    { key: "warranty", label: "Warranty", type: "chips" },
  ],
  "power-banks": [
    { key: "brand", label: "Brand", type: "select", required: true },
    { key: "capacity", label: "Capacity", type: "chips", required: true },
    { key: "output_ports", label: "Output Ports", type: "chips" },
    { key: "input_ports", label: "Input Port", type: "chips" },
    { key: "origin", label: "Origin", type: "chips", required: true },
    { key: "condition", label: "Condition", type: "chips", required: true },
    { key: "warranty", label: "Warranty", type: "chips" },
  ],
  "charging-cables": [
    { key: "brand", label: "Brand", type: "text" },
    { key: "cable_type", label: "Cable Type", type: "chips", required: true },
    { key: "length", label: "Length", type: "chips" },
    { key: "origin", label: "Origin/Quality", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "screen-protectors": [
    {
      key: "compatible_model",
      label: "Compatible Model",
      type: "text",
      required: true,
    },
    {
      key: "protector_type",
      label: "Protector Type",
      type: "chips",
      required: true,
    },
    { key: "coverage", label: "Coverage", type: "chips" },
    { key: "origin", label: "Origin", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  screens: [
    {
      key: "compatible_model",
      label: "Compatible Model",
      type: "text",
      required: true,
    },
    { key: "screen_type", label: "Screen Type", type: "chips", required: true },
    {
      key: "origin",
      label: "Origin/Authenticity",
      type: "chips",
      required: true,
    },
    { key: "condition", label: "Condition", type: "chips", required: true },
    { key: "warranty", label: "Warranty", type: "chips" },
  ],
  "mobile-stands": [
    { key: "stand_type", label: "Stand Type", type: "chips", required: true },
    { key: "material", label: "Material", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "ring-lights": [
    { key: "brand", label: "Brand", type: "select" },
    { key: "ring_size", label: "Ring Size", type: "chips", required: true },
    { key: "power_source", label: "Power Source", type: "chips" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  converters: [
    {
      key: "converter_type",
      label: "Converter Type",
      type: "chips",
      required: true,
    },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "selfie-sticks": [
    { key: "brand", label: "Brand", type: "text" },
    {
      key: "connectivity",
      label: "Connectivity",
      type: "chips",
      required: true,
    },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "stylus-pens": [
    { key: "brand", label: "Brand", type: "text" },
    {
      key: "compatible_model",
      label: "Compatible Model",
      type: "text",
      required: true,
    },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "accessory-smart-watches": [
    {
      key: "brand_model",
      label: "Brand & Model",
      type: "brand-model",
      required: true,
    },
    { key: "condition", label: "Condition", type: "chips", required: true },
    { key: "connectivity", label: "Connectivity", type: "select" },
    { key: "warranty", label: "Warranty", type: "chips" },
  ],
  "external-memory": [
    { key: "memory_type", label: "Memory Type", type: "chips", required: true },
    { key: "storage", label: "Storage", type: "select", required: true },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  keyboards: [
    { key: "brand", label: "Brand", type: "text" },
    {
      key: "keyboard_type",
      label: "Keyboard Type",
      type: "chips",
      required: true,
    },
    {
      key: "connectivity",
      label: "Connectivity",
      type: "chips",
      required: true,
    },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "smartphone-lenses": [
    { key: "lens_type", label: "Lens Type", type: "chips", required: true },
    { key: "compatible_model", label: "Compatible Model", type: "text" },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
  ],
  "app-enabled-gadgets": [
    { key: "gadget_type", label: "Gadget Type", type: "chips", required: true },
    { key: "platform_support", label: "Platform Support", type: "chips" },
    { key: "brand", label: "Brand", type: "text" },
    { key: "condition", label: "Condition", type: "chips", required: true },
    { key: "warranty", label: "Warranty", type: "chips" },
  ],
};
